### DISCUSSION TITLE
all php unit tests not running on pre-commit or pre-push

### DISCUSSION THREAD

**Discussion by alexbaron** [phpro/grumphp#1173] [Q&A] [answered]
Hello,

I try to configure grumphp to use phpunit. 
```yml
grumphp:
  ignore_unstaged_changes: true
  stop_on_failure: true
  parallel:
    enabled: true
    max_workers: 32
  fixer:
    enabled: false
    fix_by_default: false
  environment:
    files: []
    variables: {}
    paths: []
  tasks:
    composer: ~
    phpunit:
      always_execute: true
      testsuite: 'dxp-unit'
      exclude_group:
        - 'excluded-tests'
      metadata:
        priority: 101
```
        
        
 but the phpunit doesn't seem to run all the test on the pre-commit or the pre-push.

How to configure gumphp or the pre-commit hook to run all the tests ?

here the basic pre-commit generated by grumphp init

```sh
#!/bin/sh
DIFF=$(git -c diff.mnemonicprefix=false -c diff.noprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged | cat)
export GRUMPHP_GIT_WORKING_DIR="$(git rev-parse --show-toplevel)"
(cd "./" && printf "%s\n" "${DIFF}" | exec 'vendor/bin/grumphp' 'git:pre-commit' '--skip-success-output')
```
