### DISCUSSION TITLE
Possibility to override the error message on tasks

### DISCUSSION THREAD

**Discussion by Taluu** [phpro/grumphp#898] [Ideas]
| Q               | A
| --------------- | ---
| Version         | latest one ?
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no

For each tasks, instead of having a default error message (e.g the branch naming for example), having the possibility to define a custom error message would be awesome. Soething along these lines :

```yaml
parameters:
  tasks:
    git_commit_message:
      blacklist:
        - my
        - list
      whitelist:
        - my
        - whitelist
      message: "Overriding, you do not have a correct branch name. We are following the pattern [....]"
```

Could try a PR for that. Thoughts ?
