### DISCUSSION TITLE
Fix metadata attribute

### DISCUSSION THREAD

**Discussion by tom-combet** [phpro/grumphp#950] [Ideas]
| Q               | A
| --------------- | ---
| Version         | 1.5.0
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | none

It could be great to add a `fix` metadata attribute to any task, or at least a `fix` attribute for shell task.
GrumPHP would use it to autofix the code, as with PHP-CS-Fixer:

![image](https://user-images.githubusercontent.com/48719560/140619781-f29c7af4-c33b-41cb-9723-a8d1f8ccfe14.png)

**Comment by veewee** [comment]
Hello,

I'm not sure how that fix metadata attribute should work?
Most of the commands are built internally and most don't have no fix command.

You might indeed want to add a fixer for a shell task.
However, it is possible to define multiple shell tasks at once.
So I don't think it is possible to do a fix parameter for shell commands either:
https://github.com/phpro/grumphp/blob/master/doc/tasks/shell.md

Can you give me a more concrete example of what you are trying to achieve?
Maybe a custom or extending task might be a better solution for your case?

**Comment by tom-combet** [comment]
Hi,

Thanks for your fast response!
So to be very precise, I added a shell task to add license headers to my files automatically, which comes from this [repository](https://github.com/PrestaShopCorp/header-stamp). As many "code check" commands, there is a `--dry-run` option and I'm using it.
But then, I'd like that GrumPHP fixes it if I answer positively to "autofix" prompt (screenshot above). So in my case, it would run the same command without `--dry-run`.

Of course, it won't (and couldn't) be automatic. It would just be a "scripts-like" attribute, it would just execute the given scripts/commands. I see it like this:

```yaml
# grumphp.yml
grumphp:
    tasks:
        shell:
            scripts: []
            triggered_by: [php]
            fix: []
```

So for my usecase: 

```yaml
# grumphp.yml
grumphp:
    tasks:
      header-stamp:
        metadata:
          task: shell
        scripts:
          - [
              "-c",
              'vendor/bin/header-stamp --dry-run 
              --extensions="php,js,css,scss,tpl,html.twig,vue" --exclude="config,var,vendor" --license="_dev/header-stamp/afl.txt"',
            ]
        fix:
          - [
              "-c",
              'vendor/bin/header-stamp
              --extensions="php,js,css,scss,tpl,html.twig,vue" --exclude="config,var,vendor" --license="_dev/header-stamp/afl.txt"',
            ]
```

In fact, I could do a custom task (I did a composer script atm), but it makes more sense to me to have it built into the dedicated autofix tool.
