### ISSUE TITLE
[BUG?] Return empty trace for phpstan task

### ISSUE THREAD

**Issue by soulcodex** [phpro/grumphp#1004]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 1.5.0
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | N/A

**My configuration**
```yaml
# grumphp.yml
grumphp:
  hooks_dir: ~
  process_timeout: 300
  ascii: ~
  fixer:
    enabled: true
    fix_by_default: true
  tasks:
    git_blacklist:
      match_word: true
      keywords:
        - 'dd('
        - 'die('
        - 'var_dump('
        - 'exit;'
        - 'exit('
        - 'dump('
    git_commit_message:
      enforce_capitalized_subject: true
      enforce_no_subject_punctuations: false
      enforce_no_subject_trailing_period: true
      enforce_single_lined_subject: true
      max_subject_width: 60
      max_body_width: 72
    git_branch_name:
      whitelist:
        - '/^(feature|bugfix|refactor|test|update)\/\d+-.+/'
      blacklist:
        - 'release'
        - 'develop'
        - 'master'
        - 'main'
      allow_detached_head: true
    phpcsfixer2:
      config: ./.php-cs-fixer.dist.php
      verbose: true
    phpstan:
      configuration: ./phpstan.neon.dist
      level: max
```

**Steps to reproduce:**
```sh
./vendor/bin/grumphp run
```

**Result:**

- PHP Static Analysis Tool 0.12.99
- PHP CS Fixer 3.3.2
- phpstan/phpstan-symfony 0.12.44

![MicrosoftTeams-image](https://user-images.githubusercontent.com/47703157/165908012-d7754463-c0dd-4283-88fd-fc8f3eaf5e1a.png)

The phpstan trace is empty and mark the task as failed.
