### ISSUE TITLE
Git branch pattern whitelist works as "all" instead of "any"

### ISSUE THREAD

**Issue by jigarius** [phpro/grumphp#1013]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 0.18.1
| Bug?            | yes
| New feature?    | no
| Question?       | yes
| Documentation?  | no
| Related tickets | None

**My configuration**
```yaml
# grumphp.yml
tasks:
  git_branch_name:
    whitelist:
      - master
      - '/^release\/\d+\.\d+(\.x)?(-dev)?$/'
      - '/^(dev|feature|bugfix|hotfix)\/\d+-[\-|a-z|0-9]+$/'
```

**Steps to reproduce:**
```sh
git checkout -b dev/0-branch-naming
git commit -am "My commit."
```

**Result:**
```
Whitelist rule not matched: master
Whitelist rule not matched: /^release\/\d+\.\d+(\.x)?(-dev)?$/
To skip commit checks, add -n or --no-verify flag to commit command
Failed to execute command vendor/bin/grumphp git:pre-commit --skip-success-output: exit status 1
```

The first pattern in the `whitelist` matches, but grumphp still fails because the other 2 don't match. Am I doing something wrong? Also, in the long term, I'd suggest renaming `whitelist` and `blacklist` to `allow` and `deny`.
