### ISSUE TITLE
PHP8.1: Monolog\Handler\NullHandler::$level must not be accessed before initialization (git_commit_message)

### ISSUE THREAD

**Issue by sippsolutions** [phpro/grumphp#1020]
| Q               | A
| --------------- | ---
| Version         | `1.13.0`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no

I get the error `Monolog\Handler\NullHandler::$level must not be accessed before initialization` when I try to use the `git_commit_message` check. Other checks pass.

**My configuration**
(PHP 8.1)
```yaml
parameters:
  bin_dir: "./vendor/bin"
  git_dir: "."

grumphp:
  stop_on_failure: true
  ignore_unstaged_changes: false
  tasks:
    git_commit_message:
      enforce_no_subject_trailing_period: true
      enforce_single_lined_subject: true
      max_subject_width: 250
      matchers:
        Must contain issue number: /(XYZ-\d+)|(Merge)/
```

**Steps to reproduce:**
```sh
cd /tmp
mkdir test-grumphp
cd test-grumphp
php -v # use PHP 8.1!
git init
composer init
composer require phpro/grumphp
vim grumphp.yml # use my grumphp.yml
git add .
git commit -m 'XYZ-1 Test'
```

**Result:**
```
git_commit_message
==================

Typed property Monolog\Handler\NullHandler::$level must not be accessed before initialization
```

With GrumPHP 1.12.0 (and therefore Monolog 2 instead of 3) the check works (see #1014).
