### ISSUE TITLE
PhpCsFixer ignores stdout with finder defined

### ISSUE THREAD

**Issue by MeCapron** [phpro/grumphp#1027]
| Q               | A
| --------------- | ---
| Version         | 1.13.0
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  | no
| Related tickets | -

Hello,

we are using grumphp in a Gitlab CI and we are facing an issue with the configuration of PhpCsFixer.

As we have a very very large code base which contains a lot of legacy code, even in the CI we are running GrumPHP ONLY in the files that are commited to avoid exploding the memory of the CI.

To do so, we are running Grumphp this way : 

```bash
git diff --diff-filter=dr --name-only -r origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME... | php -dmemory_limit=128M ./vendor/bin/grumphp run --config=grumphp.yml
```

Howerver the PhpCsFixer is running over ALL files because of this line when you have a custom finder : 

https://github.com/phpro/grumphp/blob/v1.13.0/src/Task/PhpCsFixer.php#L96

```php
        if ($context instanceof GitPreCommitContext || !$config['config_contains_finder']) {
            $arguments->addFiles($files);
        }
```

This is running fine when we are in a GitPreCommitContext or when we don't run any finder.

Could we add a configuration to list only files from the stdout even if we have a finder on or we are not in the GitPreCommitContext?

Does anyone has maybe another idea to solve this?

**My configuration**
```yaml
grumphp:
    tasks:
        phpcsfixer:
            allow_risky: true
            config: './grumphp/.php-cs-fixer.php'
            triggered_by: [ 'php', 'phtml' ]
            config_contains_finder: true
            verbose: true
```

```php
$finder = PhpCsFixer\Finder::create()
    ->in('./app');
    
$config = new PhpCsFixer\Config();
$config->setFinder($finder)
    ->setRules([
        '@Symfony'                               => true,
        '@PHP80Migration'                        => true
    ]);

return $config;
```

**Steps to reproduce:**
- Create two files
- Run grumphp in a stdout way (like a git diff)
- Phpcsfixer will run on the two files instead of the only one you have passed in the stdout with the configuration given

**Result:**
Out of memory because running on all files
