### ISSUE TITLE
[BUG?] Return empty trace for phpmd task

### ISSUE THREAD

**Issue by palakaccorin** [phpro/grumphp#1031]
| Q               | A
| --------------- | ---
| Version         | 1.13.0
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

**My configuration**
```yaml
# grumphp.yml
    phpmd:
      ruleset: ['./dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml']
      triggered_by: [ 'php' ]
      exclude: ['dev','vendor','generated','var','lib','update','bin','pub','setup','.docker','phpserver','scripts','docker']
      metadata:
        priority: 900
```

**Steps to reproduce:**
```sh
./vendor/bin/grumphp run

```

**Result:**
![image](https://user-images.githubusercontent.com/38860012/184884438-e5cee8a2-17b8-43be-a98e-e1e96538649c.png)
