### ISSUE TITLE
Run a plain PHP script with shell task

### ISSUE THREAD

**Issue by jigarius** [phpro/grumphp#1041]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 1.5.0
| Bug?            | yes
| New feature?    | no
| Question?       | yes
| Documentation?  | yes
| Related tickets | n/a

**My configuration**
```yaml
# grumphp.yml
grumphp:
  tasks:
    shell:
      scripts:
        - scripts/foobar.php
      triggered_by: [php]
```

**Steps to reproduce:**
```sh
mkdir tmp
cd tmp
git init
echo "vendor" > .gitignore
pbpaste > grumphp.yml
composer require --dev phpro/grumphp

# Your actions
# Please add the steps on how to reproduce the issue here.

# Run GrumPHP:
./vendor/bin/grumphp run
```

Create a file `scripts/foobar.php`:
```php
#!/usr/bin/env php
<?php

echo 'Yay!' . PHP_EOL;
exit(0);
```

**Result:**
```
scripts/foobar.php: 1: cannot open ?php: No such file
To skip commit checks, add -n or --no-verify flag to commit command

```

The script is not executed as PHP. It seems to be executed in some other way.
