### ISSUE TITLE
Serialization of 'WeakMap' is not allowed after update monolog to 2.9.0

### ISSUE THREAD

**Issue by Eduardo-Morales-Alberti** [phpro/grumphp#1065]
| Q               | A
| --------------- | ---
| Version         | 1.5.1
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | [comma-separated list of related tickets](https://github.com/Seldaek/monolog/issues/1792)

**My configuration**
```yaml
grumphp:
  git_hook_variables:
    EXEC_GRUMPHP_COMMAND: docker-compose run -e'PHP_ERROR_REPORTING=E_ALL & ~E_DEPRECATED' --rm -T php
  ascii:
    failed: grumphp-ascii/grumpy.txt
    succeeded: grumphp-ascii/happy.txt
  extensions:
    - GrumphpDrupalCheck\ExtensionLoader
    - Metadrop\PhpCompatibilityTask\ExtensionLoader
  hooks_dir: ~
  tasks:
    git_commit_message:
      matchers:
        Must contain gitlab reference (if no reference use 0): '/(^SDXP2-[0-9]+:|^Merge branch.)/'
        Space and uppercase after reference: '/(^SDXP2-[0-9]+: [A-Z]|^Merge branch.)/'
      enforce_no_subject_trailing_period: true
      max_subject_width: 140
      case_insensitive: false
    phplint: ~
    yamllint: ~
    composer: ~
    jsonlint: ~
    drupalcheck: ~
    phpcs:
      encoding: utf-8
      triggered_by:
        - php
        - inc
        - module
        - install
        - profile
        - theme
        - feature
        - info
        - txt
        - md
        - js
        - test
      standard: Drupal,DrupalPractice
      ignore_patterns:
        - ./solr/*
    php_compatibility:
      testVersion: "8.1"
      triggered_by:
        - php
        - inc
        - module
        - install
```

**Steps to reproduce:**
It happens after update monolog to the last version 2.9.0.
```sh
# Generate empty folder
mkdir tmp
cd tmp
git init
echo "vendor" > .gitignore
pbpaste > grumphp.yml
composer require --dev phpro/grumphp

# Run GrumPHP:
git add -A && git commit -m"Test"
```

**Result:**
```
GrumPHP detected a pre-commit command.
GrumPHP is sniffing your code!

Running tasks with priority 0!
==============================

Running task 1/7: phplint... 
Running task 2/7: yamllint... 
Running task 3/7: composer... 
Running task 4/7: jsonlint... 
Running task 5/7: drupalcheck... 
Running task 6/7: phpcs... 
Running task 7/7: php_compatibility... 

Running task 1/7: phplint... 
Running task 2/7: yamllint... ✔
Running task 3/7: composer... 
Running task 4/7: jsonlint... 
Running task 5/7: drupalcheck... 
Running task 6/7: phpcs... 
Running task 7/7: php_compatibility... 

GrumPHP detected a commit-msg command.
GrumPHP is sniffing your code!

Running tasks with priority 0!
==============================

Running task 1/1: git_commit_message... 

Running task 1/1: git_commit_message... ✘


git_commit_message
==================

                   -:
                  -oo:
                `/oooo/`
               -+ooooooo:
             -+oooooooooo+-
           -+oooooooooooooo+-
         -+ooooooo/.`/ooooooo+-
       ./ooooooo+.    ./ooooooo+-
     `/ooooooooo        ./ooooooo/.
    -ooooooooooo:`        ./ooooooo:
   /ooooooo/ooooo+-`        -+oooooo/`
  /oooooo/` `:ooooo+-`       `/oooooo+`
 :oooooo:     `/ooooo+-`       :oooooo/
.oooooo:       `+oooooo+-`      :oooooo-
/oooooo      `:oooooooooo+.      +ooooo+
+ooooo/     -+ooooo:./ooooo/.    :oooooo
+ooooo/   .+ooooo/.   .+ooooo/`  :oooooo
/oooooo-`:ooooo/.       -oooooo-`+ooooo+
.ooooooo+ooooo:          `+ooooo+oooooo-
 /ooooooooooo+            .ooooooooooo+
 `/oooooooooo+            `oooooooooo+`
   /oooooooooo-          `+ooooooooo/`
    -+ooooooooo/.      `-+ooooooooo-
      -+oooooooooo+///+ooooooooo+:`
        .:+oooooooooooooooooo+:.
           `.:/++oooooo++/:-`

Unsupported callable: Serialization of 'WeakMap' is not allowed
To skip commit checks, add -n or --no-verify flag to commit command
```
