### ISSUE TITLE
phpcs does not detect default ruleset xml file

### ISSUE THREAD

**Issue by iMojtaba** [phpro/grumphp#1096]
| Q               | A
| --------------- | ---
| Version         | `2.0.0`
| Bug?            |  no
| New feature?    |no
| Question?       | yes
| Documentation?  |no
| Related tickets | 

I am encountering an issue with GrumPhp not detecting the PHP CodeSniffer (phpcs) ruleset file in my project. The ruleset file, named `phpcs.xml`, is located in the root directory of my project and is successfully recognized and applied when running `vendor/bin/phpcs Author.php`. However, when I use the command `php ./vendor/bin/grumphp git:pre-commit`, GrumPhp fails to detect and apply these rules. and it applies some other rules which I do not know what those are. 

I have verified that GrumPhp is properly installed and configured in my project, and I have the necessary dependencies installed. However, it seems that GrumPhp has its own ruleset file configuration or a different default ruleset file name.

I have already checked the [GrumPhp documentation](https://github.com/phpro/grumphp/blob/v2.x/doc/tasks/phpcs.md) and configuration files but could not find a solution specific to this problem. The only thing that I found is `standard` in `grumphp.yml` file and it only accepts phpcs registered styles. I tried to set it as `standard: "/full/pathto/phpcs.xml"` or `standard: "phpcs.xml"`  and none of them worked.  

Thank you in advance for your assistance and support!

**My configuration**
```yaml
grumphp:
    parallel:
        enabled: true
        max_workers: 32
    ignore_unstaged_changes: true
    tasks:
        phpcs:
            severity: ~
            error_severity: ~
            warning_severity: ~
            tab_width: ~
            report: full
            report_width: ~
            whitelist_patterns: []
            encoding: ~
            ignore_patterns: []
            sniffs: []
            triggered_by: [php]
            exclude: []
```
