### ISSUE TITLE
how can I use grum with docker-compose ?

### ISSUE THREAD

**Issue by rivassh** [phpro/grumphp#1109]
when I change execute to docker-compose, it doesn't work:
![Snapshot_2023-09-16_11-04-52](https://github.com/phpro/grumphp/assets/6438294/cb57b195-a012-445e-beed-eb0483773de2)
```
# grumphp.yml
grumphp:
  git_hook_variables:
    EXEC_GRUMPHP_COMMAND: [ '/usr/bin/docker-compose', 'exec', 'app', 'sh' ]
```

**Comment by veewee** [comment]
Does the container have php installed?
Instead of 'sh', you might need to use 'php' ?

**Comment by oallain** [comment]
Hello,

I can use : 
```yaml
grumphp:
    git_hook_variables:
        EXEC_GRUMPHP_COMMAND: docker exec -i -u DOCKER_USER -w PROJECT_DIR php
```
Where : 
* `DOCKER_USER` is the docker user (ex: root)
* `PROJECT_DIR` is le project directory (ex: /home/project/test
* `php` is the container name frome `container_name` in my docker-composer file

⚠️ After changing this value on `grumphp.yaml` you **must** launch command `vendor/bin/grumphp configure` to rewrite file `.git/hooks/pre-commit`

Hope it will help you.

Regards
