### ISSUE TITLE
git_blacklist never runs?

### ISSUE THREAD

**Issue by cerw** [phpro/grumphp#1139]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 2.5.0
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  |no
| Related tickets |

We noticed that the git_blacklist is not executing it seem its because `canRunInContext` always return false? 

**My configuration**
```yaml
grumphp:
  stop_on_failure: true
  process_timeout: 210
  parallel:
    enabled: true
    max_workers: 32
  tasks:
    file_size:
      max_size: 3M
      ignore_patterns: []
    phpcs:
      standard: PSR2
      warning_severity: 0
      error_severity: 1
      ignore_patterns:
        - ./tests
        - ./resources/*
        - ./database
        - ./bootstrap
        - ./public
        - ./config/
    git_branch_name:
      # whitelist:
      #   - '/([0-9]+)-/'
      #   - '/bugfix-*/'
      blacklist:
        - "/(shit|fuck|crap)/"
      # - "develop"
      # - "master"
    git_commit_message:
      allow_empty_message: false
      enforce_capitalized_subject: false
      enforce_no_subject_trailing_period: true
      enforce_single_lined_subject: false
      max_body_width: 400
      max_subject_width: 200
      case_insensitive: true
      multiline: true
      additional_modifiers: ""
    jsonlint: null
    phplint: null
    securitychecker_enlightn:
      lockfile: ./composer.lock
    git_blacklist:
      keywords:
        - "die("
        - "dump("
        - "dd("
        - "var_dump("
        - "exit;"
      # whitelist_patterns:
      #   - add(
      regexp_type: G
      match_word: true
    composer:

```

**Steps to reproduce:**

Put dd(); in PHP code, do `git add -y` run following
```
nanospa git:(last_bits_on_spa) ✗ git diff --cached app

─────────────────────────────────────────────────────────────────────────────────┐
app/Listeners/LogUserHasLoggedOff.php:29: public function handle(Logout $logout) │
─────────────────────────────────────────────────────────────────────────────────┘
 29 ⋮ 29 │            // no user is logged in
 30 ⋮ 30 │            return;
 31 ⋮ 31 │        }
    ⋮ 32 │        dd();
 32 ⋮ 33 │        activity()
 33 ⋮ 34 │            ->useLog('auth')
 34 ⋮ 35 │            ->event('logout')
```

```sh
./vendor/bin/grumphp run 


# Your actions
# Please add the steps on how to reproduce the issue here.

# Run GrumPHP:
git add -A && git commit -m"Test"
# or
./vendor/bin/grumphp run

```

**Result:**
```
➜  nanospa git:(last_bits_on_spa) ✗ ./vendor/bin/grumphp run
GrumPHP is sniffing your code!

Running tasks with priority 0!
==============================

Running task 1/7: file_size... ✔
Running task 2/7: phpcs... ✔
Running task 3/7: git_branch_name... ✔
Running task 4/7: jsonlint... ✔
Running task 5/7: phplint... ✔
Running task 6/7: securitychecker_enlightn... ✔
Running task 7/7: composer... ✔
             ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
           ▄▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
         ▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
  ▄▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
   ▀█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
     ▀▀▓▓▓▓▓▓▓▓▓▓▓▓█▀▀▀▀▀▀▀▀▀▀▀▀▀▀████████████▄
      ▄████████▀▀▀▀▀                 ██████████
     ███████▀                         ██████▀
      ▐████      ██▌          ██       ████▌
        ▐█▌                            ███
         █▌           ▄▄ ▄▄           ▐███
        ███       ▄▄▄▄▄▄▄▄▄▄▄▄       ▐███
         ██▄ ▐███████████████████████████
        █▀█████████▌▀▀▀▀▀▀▀▀▀██████████▌▐
          ███████████▄▄▄▄▄▄▄███████████▌
         ▐█████████████████████████████
          █████████████████████████████
           ██ █████████████████████▐██▀
            ▀ ▐███████████████████▌ ▐▀
                ████▀████████▀▐███
                 ▀█▌  ▐█████  ▐█▌
                        ██▀   ▐▀
       _    _ _                         _ _
      / \  | | |   __ _  ___   ___   __| | |
     / _ \ | | |  / _` |/ _ \ / _ \ / _` | |
    / ___ \| | | | (_| | (_) | (_) | (_| |_|
   /_/   \_\_|_|  \__, |\___/ \___/ \__,_(_)
                  |___/

```
