### ISSUE TITLE
Git Blacklist example does not work

### ISSUE THREAD

**Issue by Jamesking56** [phpro/grumphp#1149]
| Q               | A
| --------------- | ---
| Version         | `2.6.0`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | yes
| Related tickets | 

**My configuration**
```yaml
# grumphp.yml
grumphp:
    tasks:
        git_blacklist:
            keywords:
                - "die\\("
                - "dd\\("
                - "var_dump\\("
                - "exit;"
                - "file_put_contents\\("
            triggered_by: ['php']
            regexp_type: G
```

**Steps to reproduce:**
```sh
# Generate empty folder
mkdir tmp
cd tmp
git init
echo "vendor" > .gitignore
pbpaste > grumphp.yml
composer require --dev phpro/grumphp

# Your actions
# Please add the steps on how to reproduce the issue here.
Add config file from above

# Run GrumPHP:
git add -A && git commit -m"Test"
# or
./vendor/bin/grumphp run
```

**Result:**
```
git_blacklist
=============

Something went wrong:
fatal: -e option, 'die\(': Unmatched ( or \(
```

This config matches the config in the docs here: https://github.com/phpro/grumphp/blob/v2.x/doc/tasks/git_blacklist.md
