### ISSUE TITLE
Set path and/or full filename in triggered_by

### ISSUE THREAD

**Issue by evs-xsarus** [phpro/grumphp#1157]
| Q               | A
| --------------- | ---
| Version         | 2.5.0
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

Due to the use of dockers, my grump config only uses shell tasks , example:

```yaml
grumphp:
    process_timeout: 512
    tasks:
        magento_composer:
            scripts:
                - ["-c", "/usr/local/bin/composer2 --working-dir=./magento validate"]
            metadata:
                task: shell
        magento_stan-check:
            scripts:
                - ["-c", "/usr/local/bin/composer2 --working-dir=./magento stan-check"]
            metadata:
                task: shell

        integrations_composer:
            scripts:
                - ["-c", "/usr/local/bin/composer2 --working-dir=./integrations validate"]
            metadata:
                task: shell
        integrations_cs-check:
            scripts:
                - ["-c", "/usr/local/bin/composer2 --working-dir=./integrations cs-check"]
            metadata:
                task: shell
```

Most of these tasks start properly when PHP files are changed as per documentation https://github.com/phpro/grumphp/blob/v2.x/doc/tasks/shell.md  for triggered_by .

Sadly, the `composer validate` is not triggered if only composer.json/composer.lock is changed. I can add these:

```yaml
        magento_composer:
            scripts:
                - ["-c", "/usr/local/bin/composer2 --working-dir=./magento validate"]
            metadata:
                task: shell
            triggered_by: [json, lock]
```
But that means the task will run even if a non-related json or lock file is changed.

To avoid this, specifying a complete filename should help as in this example:

```yaml
            triggered_by: [composer.lock, composer.json]
```

or even with wildcards:

```yaml
            triggered_by: [composer.*]
```

As you can see in my example, I've duplicate tasks but for different folders. The path should be definable too in triggered by, full example:

```yaml
        magento_composer:
            scripts:
                - ["-c", "/usr/local/bin/composer2 --working-dir=./magento validate"]
            metadata:
                task: shell
            triggered_by: ['./magento/composer.*']
```

**Comment by veewee** [comment]
Hello @evs-xsarus,

That would be possible. We do a similir thing for the `ComposerRequireChecker` task.
However : since we are now filtering `triggered_by` as extensions, it would be considered a BC break.
Maybe an alternate solution could be to introduce a new parameter for this specific case? Something like `triggered_by_filenames` (which will use the `$files->names()` filter)?

Feel free to propose changes in a PR.

**Comment by evs-xsarus** [comment]
@veewee could you have a look at my draft MR?

**Comment by evs-xsarus** [comment]
@veewee I've refactored a bit and applied the same approach as in SymfonyConsole. That whilelist + ignore pattern works great as can be tested with this configuration:

```yaml
grumphp:
    process_timeout: 360
    tasks:
        magento_composer:
            triggered_by: ['json', 'lock']
            whitelist_patterns:
                - "#^magento/composer.json#"
                - "#^magento/composer.lock#"
            scripts:
                - ["-c", "/usr/local/bin/composer2 --working-dir=./magento validate"]
            metadata:
                task: shell
```
