### ISSUE TITLE
GrumPHP phpcs not picking up for "old" files

### ISSUE THREAD

**Issue by Yerlix** [phpro/grumphp#117]
I'm testing GrumPHP for Drupal, and I've downloaded Drupal Coder Sniffer (https://www.drupal.org/node/1419988) with a ruleset for phpcs. I've installed it locally, not global like they do in the guide.

Now I've noticed that for instance the `dpm('test');` function is picked up when I create a new file (not known to Git) and commit it. 
But when I've added the same function to an old file (known to Git), GrumPHP did not show an error for it when committing.

Now I've tested it again, because I thought that GrumPHP only triggered for new files. But when I try to add some other function (for instance `dsm('test')` to the "new" file, which is committed now, GrumPHP shows an error on commit.

My configuration for GrumPHP:
```
parameters:
  git_dir: .
  bin_dir: ./vendor/bin
  tasks:
    git_commit_message:
      matchers:
          - /BT-([0-9]*)/
    phpcs:
      standard: vendor/drupal/coder/coder_sniffer/Drupal/
      ignore_patterns:
        - cfg/
        - libraries/
```
