### ISSUE TITLE
PHPStan task always succeeds in GrumPHP 2.12.0, even with errors (Windows/Git Bash)

### ISSUE THREAD

**Issue by WladGin** [phpro/grumphp#1172]
### **Problem Description:**

I am encountering an issue where the phpstan task in GrumPHP (version 2.12.0) consistently reports success (✔) even when PHPStan itself returns a non-zero exit code (indicating errors). This prevents GrumPHP from failing the commit as expected. Same story with composer_normalize and securitychecker_composeraudit, while phpcsfixer and git_blacklist work and show errors if there are any

**Steps to Reproduce:**

### Environment:

**OS:** Windows 10
**Terminal:** Git Bash
**PHP Version:** PHP 8.3.6
**Composer Version:** 2.8.9 
**GrumPHP Version:** 2.12.0
**PHPStan Version:** 2.1.17

```
grumphp:
  fixer:
    enabled: true
    fix_by_default: true
  tasks:
    composer_normalize:
      indent_size: ~
      indent_style: ~
      no_update_lock: false
      verbose: false
    phpcsfixer:
      allow_risky: ~
      cache_file: ~
      config: .php-cs-fixer.dist.php
      rules: [ ]
      using_cache: ~
      config_contains_finder: true
      verbose: true
      diff: false
      triggered_by: [ 'php' ]
    phpstan:
      autoload_file: ~
      configuration: phpstan.neon.dist
      level: null
      force_patterns: [ ]
      ignore_patterns: [ ]
      triggered_by: [ 'php' ]
      memory_limit: "-1"
      use_grumphp_paths: false
    securitychecker_composeraudit:
      format: table
      locked: true
      no_dev: false
      run_always: true
```

```
phpstan.neon.dist
includes:
    - ./vendor/phpstan/phpstan-deprecation-rules/rules.neon
    - ./vendor/nesbot/carbon/extension.neon
    - ./vendor/larastan/larastan/extension.neon
    - ./phpstan-baseline.neon

parameters:
    # The level 9 is the highest level
    level: 8
```

1) Create a PHP file with a known PHPStan error:
E.g., create app/TestError.php with content like:

```
<?php

namespace App;

class TestError
{
    public function doSomething(string $param): int
    {
        return $123; // This will cause a PHPStan error
    }
}
```
2) Run PHPStan directly from the command line:
`php vendor/bin/phpstan.phar analyse --configuration=phpstan.neon.dist --memory-limit=-1 --no-ansi --no-interaction --no-progress`

Expected Result: PHPStan reports errors and exits with a non-zero exit code (e.g., 1). (Please provide the exact output and exit code if possible).
Actual Result (confirmed): PHPStan reports errors (e.g., "Undefined variable: $123") and returns exit code 1.

3)Run GrumPHP:
`php vendor/bin/grumphp run -vvv`

Expected Result: The phpstan task should fail (✘) and GrumPHP should report the failure.
Actual Result: The phpstan task shows ✔ (success), despite PHPStan returning an error.

**Additional Notes:**
Other GrumPHP tasks, such as phpcsfixer, correctly report failure (✘) when errors are detected. This suggests the issue is specific to the phpstan task's handling of exit codes in this version of GrumPHP.

**GrumPHP**
```
$ php vendor/bin/grumphp run -vvv
Config file: D:\OSPanel\home\tarot-app\grumphp.yml
Working dir: D:\OSPanel\home\tarot-app
Project dir: D:\OSPanel\home\tarot-app
GIT working dir: D:/OSPanel/home/tarot-app
GIT repository dir: D:/OSPanel/home/tarot-app\.git
Bin dir: D:\OSPanel\home\tarot-app\vendor\bin
Composer file: D:\OSPanel\home\tarot-app\composer.json
[2025-05-26T20:54:28.546620+03:00] GrumPHP.DEBUG: Repository created (git dir: "D:\OSPanel\home\tarot-app\.git", working dir: "D:/OSPanel/home/tarot-app") [] []
[2025-05-26T20:54:28.547814+03:00] GrumPHP.INFO: run command: ls-files "D:\OSPanel\home\tarot-app"  [] []
[2025-05-26T20:54:28.758008+03:00] GrumPHP.DEBUG: last command (ls-files) duration: 210.01ms [] []
[2025-05-26T20:54:28.758250+03:00] GrumPHP.DEBUG: last command (ls-files) return code: 0 [] []
[2025-05-26T20:54:28.758386+03:00] GrumPHP.DEBUG: last command (ls-files) output: .dockerignore .editorconfig .env.example .gitattributes .gitignore .php-cs-fixer.dist.php README.md app/Casts/LocationStringCast.php [....list of project files.....] [] []
GrumPHP is sniffing your code!

Running tasks with priority 0!
==============================

Running task 1/4: composer_normalize...
Running task 2/4: phpcsfixer...
Running task 3/4: phpstan...
Running task 4/4: securitychecker_composeraudit...

Command: D:\OSPanel\modules\PHP-8.3\ospanel_data\default_data\composer\composer.phar normalize --dry-run

Command: D:\OSPanel\home\tarot-app\vendor\bin\phpstan.phar analyse --configuration=phpstan.neon.dist --memory-limit=-1 --no-ansi --no-interaction --no-progress
Running task 1/4: composer_normalize... ✔
Running task 2/4: phpcsfixer...
Running task 1/4: composer_normalize... ✔
Running task 2/4: phpcsfixer... ✘
Running task 3/4: phpstan... ✔
Running task 4/4: securitychecker_composeraudit... ✔
```

![Image](https://github.com/user-attachments/assets/1657ed2c-d2a1-407c-bf0a-8e36b4259d6a)

**Сomposer normalized**

![Image](https://github.com/user-attachments/assets/b91ab70b-1ecf-4d75-82b7-9435d337f117)

PhpStan

![Image](https://github.com/user-attachments/assets/f45d513a-3057-4244-84ac-6d24bf27b64c)
