### ISSUE TITLE
phpcs specific directory only

### ISSUE THREAD

**Issue by mgeoffray** [phpro/grumphp#158]
| Q | A |
| --- | --- |
| Branch | / |
| Bug? | no |
| New feature? | no |
| Question? | yes |
| Documentation? | no |
| Related tickets | / |

Is there a way to specify path(s) to inspect for phpcs instead of ignore_patterns configuration ?
My case is that I am using the documentation configuration for a Symfony2 :

``` yaml
phpcs:
   standard: "./vendor/leaphub/phpcs-symfony2-standard/leaphub/phpcs/Symfony2/"
   show_warnings: true
   ignore_patterns: ["*/app/*","*/bin/*","*/tests/*","*/utils/*","*/var/*","*/vendor/*","*/web/*"]
```

The thing is that grumphp run phpcs over all Symfony files if I am not configuring `ignore_patterns` and I would like to configure this in a more efficient way that writing all the directories that I have to ignore. 
I would like to specify only my `/src/` directory like it is possible with the phpcs CLI.

Thank you !
