### ISSUE TITLE
Sort tasks by priority in the TaskRunner

### ISSUE THREAD

**Issue by veewee** [phpro/grumphp#16]
In a Task service it must be possible to add a "priority" tag to the service configuration.
E.g.:

```yml
parameters:
    tasks:
        taskname:
            metadata:
                priority: 1000
```

The higher the priority, the earlier the task is executed.
The tasks will be sorted during runtime in the TasksCollection or in the TasksComilerPass.

The metadata functionallity is already available with the `getTaskMetadata()` method on the GrumPHP object.

More information: https://github.com/phpro/grumphp/blob/master/doc/tasks.md#metadata
