### ISSUE TITLE
No match for regexp /diff --git (a\/.*) (b\/.*)\n/ 

### ISSUE THREAD

**Issue by nWidart** [phpro/grumphp#164]
| Q               | A
| --------------- | ---
| Branch          | 0.9.1
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

Hi,

I installed GrumPHP with one task, php-cs-fixer, and when commiting a file, it shows the following error.

<img width="811" alt="screen shot 2016-07-28 at 16 03 50" src="https://cloud.githubusercontent.com/assets/882397/17215624/c9a24c00-54dd-11e6-9d06-48c0df18e7d6.png">

However when I run `php ./vendor/bin/grumphp run` it works as expected.

**My configuration**
```yaml
parameters:
    git_dir: .
    bin_dir: vendor/bin
    tasks:
      phpcsfixer:
        config_file: .php_cs

```

- Run GrumpHP:
- git add . 
- git commit composer.json "Test"

**Result:**

```
[Gitonomy\Git\Exception\RuntimeException]                                                    
  No match for regexp /diff --git (a\/.*) (b\/.*)\n/ Upcoming: diff --git c/composer.json i/c 
```
