### ISSUE TITLE
phpunit task group option

### ISSUE THREAD

**Issue by Kanti** [phpro/grumphp#166]
| Q               | A
| --------------- | ---
| Branch          | /
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | no
| Related tickets | /

**About:**
Could we get an option for the phpunit task that could specify the groups the would like to run?
it would be very helpful.

**something like this:**
```yaml
# grumphp.yml
    phpunit:
      config_file: tests/phpunit.xml
      groups: [small, fast]
      metadata:
        priority: 200
```
