### ISSUE TITLE
Aborting on Phpcs task

### ISSUE THREAD

**Issue by jtgrimes** [phpro/grumphp#179]
| Q               | A
| --------------- | ---
| Branch          | 0.9.1
| Bug?            | yes
| New feature?    | no
| Question?       | yes
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

**My configuration**
```yaml
# grumphp.yml
parameters:
    bin_dir: "./vendor/bin"
    git_dir: "."
    hooks_dir: ~
    hooks_preset: local
    stop_on_failure: true
    ignore_unstaged_changes: false
    process_timeout: 240
    ascii:
        failed: ~
        succeeded: ~
    tasks:
#        composer: ~
#        git_blacklist: ~
#        git_commit_message: ~
        phpcs:
            standard: PSR2
            show_warnings: true
            tab_width: ~
            ignore_patterns:
              - tests/
              - database/
              - features/
              - autoload.php
              - .blade.php
              - resources/lang
            sniffs: []
            triggered_by: [php]
        phpunit: ~
#        behat:
#            config: ~
#            format: progress
#            stop_on_failure: false
    extensions: []
```

**Steps to reproduce:**
```sh
vendor\bin\grumphp run
```
Running on Windows, works fine on the same machine on other repos so it's not a PHP configuration issue

**Result:**
```
GrumPHP is sniffing your code!
Running task 1/2: Phpcs
Aborted ...
```

**Question**
Is there any way to have grumphp log what it's doing so that I don't have to step through code to figure out more about why this isn't working?
