### ISSUE TITLE
grumphp errors on gherkin task with error 'Finding files on features'

### ISSUE THREAD

**Issue by bizmate** [phpro/grumphp#194]
| Q               | A
| --------------- | ---
| Branch          | 0.9.4
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no

**My configuration**
```yaml
# grumphp.yml
# Please add a copy of your grumphp.yml file.
parameters:
    git_dir: ../
    bin_dir: vendor/bin
    stop_on_failure: true
    tasks:
      gherkin:
        directory: 'features'
        align: left
      phpcs:
        standard: PSR2
        show_warnings: false
        tab_width: ~
        ignore_patterns:
          - bootstrap/cache/
          - database/
          - features/
        sniffs: []
        triggered_by: [php]
      securitychecker: ~
```

**Steps to reproduce:**
```sh
# Generate empty folder after installing grump
composer require --dev phpro/grumphp
echo 'some gherkin feature and code' > features/suite/dosomething.feature

# Your actions
# Please add the steps on how to reproduce the issue here.

# Run GrumpHP:
./vendor/bin/grumphp run
```

**Result:**
```
# Please add the result of the run or git commit actions here.
GrumPHP is sniffing your code!
Running task 1/3: Gherkin
Aborted ...
             ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
           ▄▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
         ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄
        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
       ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
  ▄███▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 █▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
   ▀█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
     ▀▀▓▓▓▓▓▓▓▓▓▓▓▓█▀▀▀▀▀▀▀▀▀▀▀▀▀▀████████████▄
      ▄███████                       ██████████
     ███████▀  ▀▀▀▀▀▄      ▄▀▀▀▀▀     █████ ▀
      ▐████      ▐██        ▐██        ████▌
      ████▌                            ███
       ▌██▌           ▄▄ ▄▄           ▐███
        ███       ▄▄▄▄▄▄▄▄▄▄▄▄       ▐███
         ██▄ ▐███████████████████████████
        █▀███████████▀     ▀▀███████████
          ██████████▄███████▄███████████
         ▐█████████████████████████████
          █████████████████████████████
           ██ █████████████████████▐██▀
            ▀ ▐███████████████████▌ ▐▀
                ████▀████████▀▐███
                 ▀█▌  ▐█████  ██▌
                        ██▀   ▐▀

       ██████████████████████████████████
       █░░░░░░▀█▀░░░░░░▀█░░░░░░▀█▀░░░░░▀█
       █░░▐█▌░░█░░░██░░░█░░██░░░█░░░██░░█
       █░░▐█▌░░█░░░██░░░█░░██░░░█░░░██░░█
       █░░▐█▌░░█░░░██░░░█░░░░░░▄█░░▄▄▄▄▄█
       █░░▐█▌░░█░░░██░░░█░░░░████░░░░░░░█
       █░░░█░░░█▄░░░░░░▄█░░░░████▄░░░░░▄█
       ██████████████████████████████████

Finding files on features
To skip commit checks, add -n or --no-verify flag to commit command
```

I have also tried to downgrade to other versions 0.9.1. Not sure what is happening but this was working before. If I remove the grump config the other tasks run ok.
