### ISSUE TITLE
Add filter_staged_files to PhpCS task

### ISSUE THREAD

**Issue by mgeoffray** [phpro/grumphp#230]
| Q               | A
| --------------- | ---
| Branch          | master for features and deprecations
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  | yes/no
| Related tickets | comma-separated list of related tickets

Is that possible for PhpCS task to filter only the staged file on commit ?    
Actually since last pull request it is possible to add whitelist to FileCollection but I would like to know if it is possible to filter on modified / staged to commit file only ?    
   
If not here is my proposal, a new boolean option **filter_staged_files** :    
```yml
phpcs:
    filter_staged_files: true
    standard: "./vendor/leaphub/phpcs-symfony2-standard/leaphub/phpcs/Symfony2/"
    show_warnings: true
    whitelist_patterns:
        - /^src\/(.*)/
    triggered_by: [php]
```

#### If false *(default)*  
filter is not enabled, all files will be processed as normal    
    
#### If true  
filter is enabled, only staged for commit files will be processed
