### ISSUE TITLE
Custom banners

### ISSUE THREAD

**Issue by Grafikart** [phpro/grumphp#237]
| Q               | A
| --------------- | ---
| Branch          | master
| Bug?            | yes

I tried to set custom banners but ended up with an error.

**My configuration**
```yaml
# grumphp.yml
parameters:
  ascii:
    failed: ko.txt
    succeeded: ok.txt
  git_dir: .
  bin_dir: vendor/bin
  tasks:
    phplint: ~
    phpcsfixer2: ~
    phpunit:
      always_execute: true
```

**Result:**

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to GrumPHP\Util\Filesystem::readFromFileInfo() must be an instance of SplFileInfo, string given
```

In my opinion you should allow string for this method https://github.com/phpro/grumphp/blob/master/src/GrumPHP/Util/Filesystem.php#L19 or convert information from configuration to SplFileInfo
