### ISSUE TITLE
Error after removing a file

### ISSUE THREAD

**Issue by Henk8** [phpro/grumphp#242]
| Q               | A
| --------------- | ---
| Branch          | master
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

**My configuration**
```yaml
parameters:
    bin_dir: "./vendor/bin"
    git_dir: "."
    stop_on_failure: true
    tasks:
        phpcs:
            standard: "PSR2"
```

**Steps to reproduce:**
create a new file and add it to your git repository. 
Commit the file.
Remove the file an try to commit your project again.

**Run GrumpHP:**
git add -A && git commit -m"Test"

**Result:**

```
</fg=red>
ERROR: The file "new_file.php" does not exist.
```
