### ISSUE TITLE
Question or issue about die() function blacklisted in Phpparser

### ISSUE THREAD

**Issue by brunoauger** [phpro/grumphp#243]
| Q               | A
| --------------- | ---
| Bug?            | no
| New feature?    | yes ?
| Question?       | yes

Hello, I'm trying to remove all die() or exit() from my code....

**My configuration**
```
parameters:
    bin_dir: "./vendor/bin"
    git_dir: "."
    tasks:
        phpcs:
            standard: PSR2
            show_warnings: false
        yamllint: ~
        phplint: ~
        phpcsfixer: ~
        phpparser:
            visitors:
                forbidden_function_calls:
                    blacklist:
                        - 'var_dump'
                        - 'dump'
                        - 'die'

```
It doesn't work... for the function die()
So I did that in:
_vendor/phpro/grumphp/src/GrumPHP/Parser/Php/Visitor/ForbiddenFunctionCallsVisitor.php_

```
    public function leaveNode(Node $node)
    {

        if($node instanceof Node\Expr\Exit_){
            $this->addError(
                sprintf('Found blacklisted "%s" function call', 'die or exit'),
                $node->getLine(),
                ParseError::TYPE_ERROR
            );
            return;
        }

        if (!$node instanceof Node\Expr\FuncCall) {
            return;
        }

        $function = $node->name;
        if (!in_array($function, $this->blacklist)) {
            return;
        }

        $this->addError(
            sprintf('Found blacklisted "%s" function call', $function),
            $node->getLine(),
            ParseError::TYPE_ERROR
        );
    }
```
And it works as expected!

**Improvement**
I would like to avoid override the bundle...Workable ?
