### ISSUE TITLE
Impossible to run custom NPM scripts

### ISSUE THREAD

**Issue by Anahkiasen** [phpro/grumphp#250]
| Q               | A
| --------------- | ---
| Branch          | 0.11.0 
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

**My configuration**
```yaml
parameters:
    git_dir: .
    bin_dir: ./vendor/bin
    tasks:
        npm_script:
            script: run lint
            triggered_by: [js]
            working_directory: "./"
```

**Steps to reproduce:**

Run Grumphp

**Result:**

In NPM, you can add custom scripts to the `package.json` file. Custom being any scripts that are not core scripts (npm build, npm test, etc). To run those, you call `npm run {name of script}`.

Issue is currently Grumphp runs `npm 'run lint'` instead of `npm run lint`, which fails.
