### ISSUE TITLE
Grumphp Stripping away important signs for phpcsFixer2 rules (@ and making it lowercase)

### ISSUE THREAD

**Issue by j3rrey** [phpro/grumphp#281]
| Q               | A
| --------------- | ---
| Branch          | master
| Bug?            | yes
| New feature?    | no
| Question?       | yes/no
| Documentation?  | no

I opened the issue on the PHP CS Fixer Repo

https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2518

I'm digging into the Grumphp code trying to find the place where the @ get's stripped away 

**My configuration**
```yaml
parameters:
    bin_dir: "./vendor/bin"
    git_dir: "."
    hooks_dir: ~
    hooks_preset: local
    stop_on_failure: false
    ignore_unstaged_changes: false
    process_async_limit: 10
    process_async_wait: 1000
    process_timeout: 60
    ascii:
        failed: grumphp-grumpy.txt
        succeeded: grumphp-happy.txt
    tasks:
        git_blacklist:
            keywords:
                - "die("
                - "var_dump("
                - "print_f("
                - "dump("
                - "dd("
                - "exit;"
            triggered_by: ["php"]
        git_commit_message:
            matchers:
                - /SER-([0-9]*)/
            case_insensitive: true
            multiline: true
            additional_modifiers: ''
        git_conflict: ~
        phpcsfixer2:
            allow_risky: false
            cache_file: ~
            config: ~
            rules: ["@Symfony"]
            using_cache: false
            path_mode: ~
            verbose: true
        phpmd:
            exclude: []
            ruleset: ['cleancode', 'codesize', 'naming']
            triggered_by: ["php"]
        phpparser:
            ignore_patterns: []
            kind: php7
            triggered_by: ["php"]
            visitors: {}
        phpunit: ~
        phpversion:
            project: "7.0"
        shell: ~

    testsuites: []
    extensions: []
```

One can make a workaround with a config file! 

php_cs.dist
```
<?php

$finder = PhpCsFixer\Finder::create()
    ->exclude(['exclude/path'])
    ->name('*.php');

return PhpCsFixer\Config::create()
    ->setRules([
        '@Symfony' =>  true,
        'encoding' => false,
        'psr0' => false,
        'psr4' => false,
        'self_accessor' => false,
        'no_short_echo_tag' => true,
        'array_syntax' => ['syntax' => 'short'],
    ])
    ->setFinder($finder);
```

This will execute the cs fixer with the given values and won't strip away any of the rules important characters!

Updated grumphp.yml
```
parameters:
    bin_dir: "./vendor/bin"
    git_dir: "."
    hooks_dir: ~
    hooks_preset: local
    stop_on_failure: false
    ignore_unstaged_changes: false
    process_async_limit: 10
    process_async_wait: 1000
    process_timeout: 60
    ascii:
        failed: grumphp-grumpy.txt
        succeeded: grumphp-happy.txt
    tasks:
        git_blacklist:
            keywords:
                - "die("
                - "var_dump("
                - "print_f("
                - "dump("
                - "dd("
                - "exit;"
            triggered_by: ["php"]
        git_commit_message:
            matchers:
                - /SER-([0-9]*)/
            case_insensitive: true
            multiline: true
            additional_modifiers: ''
        git_conflict: ~
        phpcsfixer2:
            allow_risky: false
            cache_file: ~
            config: config/php_cs.dist
            rules: []
            using_cache: false
            path_mode: ~
            verbose: true
        phpmd:
            exclude: []
            ruleset: ['cleancode', 'codesize', 'naming']
            triggered_by: ["php"]
        phpparser:
            ignore_patterns: []
            kind: php7
            triggered_by: ["php"]
            visitors: {}
        phpunit: ~
        phpversion:
            project: "7.0"
        shell: ~

    testsuites: []
    extensions: []
```
