### ISSUE TITLE
PHP-CS-Fixer rules specifying standards cannot be specified

### ISSUE THREAD

**Issue by Bilge** [phpro/grumphp#287]
| Q               | A
| --------------- | ---
| Branch          | v0.11.1
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | n/a

**My configuration**
```yaml
parameters:
  tasks:
    phpcsfixer2:
      rules:
        - '@PSR2'
```

**Steps to reproduce:**
```sh
git commit -a
```

**Result:**
```

  [PhpCsFixer\ConfigurationException\InvalidConfigurationException (16)]
  The rules contain unknown fixers (psr2).

```

**Observation:**

It appears the leading *at* (`@`) symbol is dropped from the command line invocation.
