### ISSUE TITLE
Run same task twice with different configuration

### ISSUE THREAD

**Issue by Bilge** [phpro/grumphp#309]
| Q               | A
| --------------- | ---
| Version         | 0.11.1
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | n/a

One may wish to run some tasks twice with different configurations. For example, run phpcs with warnings treated as errors for some directories and with warnings disabled for different directories. However, this GrumPHP configuration uses the task name as the configuration key, so it is not possible to specify the same task twice due to the format of the configuration.

**Comment by veewee** [comment]
I am not in favour of this option since it is making the configuration part very difficult. Currently it is very easy to get the project up and running with some basic configuration. If you want this kind of advanced solutions, you might just want to create a spefic task for your use case?

Feel free to add some thoughts on how you see the configuration part. Maybe it is not clear to me at the moment.

**Comment by Bilge** [comment]
Presently I haven't put any thought into how the configuration should look, I just wanted to open the discussion on whether this is something we want to support.

**Comment by patkar** [comment]
We ran in this issue too. We have two phpcsfixer config files. One `.php_cs` file for all files except some special TYPO3 files. And a `.typo3.php_cs` with the same settings as the previous one except `declare_strict_types`. So we need to run phpcsfixer two times with the different config files. Sadly the special TYPO3 files are requiring this.

I could imagine the following enhancement as example to the config:

```yaml
parameters:
    git_dir: .
    bin_dir: vendor/bin
    tasks:
        phpcsfixer2:
            allow_risky: true
            path_mode: intersection
            triggered_by: ['php']
        phpcsfixer2_typo3:
            task: phpcsfixer2
            allow_risky: true
            config: .typo3.php_cs
            path_mode: intersection
            triggered_by: ['php']
```

As you can see, if there is a task parameter in the config, the key of the config will be ignored and the value of the task parameter will be used instead. No BC break and the easy of configuration stays. But special snowflakes ( :trollface: ) like me and others in need can use the extended syntax :grimacing:

**Comment by szinya** [comment]
I could use this too. We have separate phpmd configs for the project files and the tests. With the changes proposed by @patkar our grumphp.yml would look something like this:

```yaml
parameters:
    tasks:
        phpmd:
            exclude: [tests]
            ruleset: [phpmd.xml.dist]
        phpmd_tests:
            task: phpmd
            exclude: [src]
            ruleset: [phpmd_tests.xml.dist]
```

However, since the current implementation is built around unique registered tasks I understand that this simple change would require significant work to do. Still, I think it would greatly improve the versatility of GrumPHP.

**Comment by patkar** [comment]
Since we build a convention checker repository based on GrumPHP, it was easy to find a workaround which doesn't need to be copied in every repo we have. Similar to their example https://github.com/linkorb/conventions-checker

In our `common/grumphp.yml`:
```yaml
services:
    task.phpcsfixer2_typo3:
        class: Acme\Typo3\ConventionsChecker\Task\PhpCsFixerV2Typo3
        arguments:
            - '@config'
            - '@process_builder'
            - '@async_process_runner'
            - '@formatter.php_cs_fixer'
        tags:
            - {name: grumphp.task, config: phpcsfixer2_typo3}
```

You need this extra class, because every tasks gets it configuration via `$this->grumPHP->getTaskConfiguration($this->getName());`, where `getName()` returns the config key in the `parameters.tasks` array. The `config` key in the service definition tag is only used in the compiler pass to not instantiate tasks which are not configured. After this `getName()` is asked to get the task config from the container. Which can lead to minor inconsistencies in some cases. And thus we need to extend the original fixer:

```php
<?php

namespace Acme\Typo3\ConventionsChecker\Task;

use GrumPHP\Task\PhpCsFixerV2;

class PhpCsFixerV2Typo3 extends PhpCsFixerV2
{
    public function getName(): string
    {
        return 'phpcsfixer2_typo3';
    }
}
```
