### ISSUE TITLE
Add `import:` property

### ISSUE THREAD

**Issue by ademarco** [phpro/grumphp#330]
| Q               | A
| --------------- | ---
| Version         | `0.11.3`
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  | no
| Related tickets | 

In our organisation we want to enforce code quality by packaging together all our conventions in a single package that developers will just include in their projects by requiring it via Composer, exactly like [Conventions Checker](https://github.com/linkorb/conventions-checker) is doing.

The only difference is that we still want teams to tweak some of the conventions (for instance commit message styles with their Jira project prefix instead of GitHub issue number).

I was wondering if it would be possible to add an `import:` property that would import a "parent" `grumphp.yml` and have the local file to override or add tasks and other configuration options: essentially the two files will be merged before being processed by GrumPHP.

So if the "parent" `grumphp.yml` file is:

```yaml
# ./vendor/my-vendor/code-review/dist/grumphp.yml.dist
parameters:
  tasks:
    git_commit_message:
      matchers:
        - '/^#\d+: [A-Z].+\./'
      case_insensitive: false
      multiline: false
```

And the local project `grumphp.yml` would look like:

```yaml
# ./grumphp.yml.dist
parameters:
  import: ./vendor/my-vendor/code-review/dist/grumphp.yml.dist
  tasks:
    git_commit_message:
      matchers:
        - '/^JIRA-\d+: [A-Z].+\./'
```

Then the actual configuration would look like:

```yaml
parameters:
  tasks:
    git_commit_message:
      matchers:
        - '/^JIRA-\d+: [A-Z].+\./'
      case_insensitive: false
      multiline: false
```

**Comment by veewee** [comment]
Since we are using the Symfony container, I think it should be possible with following syntax:

```yml
imports:
    - { resource: some/other/grumphp.yml }
parameters:
    youcustomconfig: here
```

More info: http://symfony.com/doc/current/service_container/import.html

Can you verify if this is working for you?

**Comment by ademarco** [comment]
Ok that worked! :D Thank you!

**Comment by ademarco** [comment]
Actually, after running some more tests, it looks like you can only replace parameters properties and not merge them, which is totally acceptable, only do we want to provide merging at all? Or the default Symfony configuration import is enough?

**Comment by veewee** [comment]
How do you see that exactly?
I think the current implementation of the config file is pretty extendable.
Maybe it's another solution to use parameters in the convention grumphp.yml file which you can customize in the project specific file?

For example:

```yml
# Project grumphp.yml
imports:
    - { resource: global/grumphp.yml }
parameters:
    convention.git_commit_message_matchers: ['/^JIRA-\d+: [A-Z].+\./']
```

```yml
# Global grumphp.yml
parameters:
  tasks:
    git_commit_message:
      matchers: "%convention.git_commit_message_matchers%"
      case_insensitive: false
      multiline: false
```

**Comment by ademarco** [comment]
Right that would work well I guess, meaning that the parent `grumphp.yml` will "parametize" all values that can be extended, so that child `grumphp.yml` will just override them as you propose above and, if they really want to override all the task, then they can always rewrite it entirely.

I think this is the cleanest solution, we just need to add documentation and we are done. Thanks!

**Comment by ademarco** [comment]
Actually we don't even need to parametize them, they are already parameters, so it's enough doing:

```yaml
imports:
    - { resource: global/grumphp.yml }
parameters:
  tasks.git_commit_message.matchers ['/^JIRA-\d+: [A-Z].+\./']
```

And this will only override the commit message regular exp. for instance. :)

**Comment by ademarco** [comment]
Ok, back to square one! 

It turns out we need to parametize them in order for them to be overridable, so the working solution is the one you suggested at https://github.com/phpro/grumphp/issues/330#issuecomment-287352771

```yaml
# Project grumphp.yml
imports:
    - { resource: convention/grumphp.yml }
parameters:
    convention.git_commit_message_matchers: ['/^JIRA-\d+: [A-Z].+\./']
```

```yaml
# Convention grumphp.yml
parameters:
  convention.git_commit_message_matchers: ['/.*/']
  tasks:
    git_commit_message:
      matchers: "%convention.git_commit_message_matchers%"
      case_insensitive: false
      multiline: false
```
