### ISSUE TITLE
git_conflict rules crashes on latest version

### ISSUE THREAD

**Issue by Anahkiasen** [phpro/grumphp#340]
| Q               | A
| --------------- | ---
| Version         | 0.11.4
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

**My configuration**
```yaml
parameters:
    git_dir: .
    bin_dir: ./vendor/bin
    tasks:
        git_conflict: ~
```

**Result:**
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function GrumPHP\Task\AbstractExternalTask::__construct(), 1 passed and exactly 3 expected in /Users/anahkiasen/Sites/stappler/aromatech-extranet-reactor/vendor/phpro/grumphp/src/Task/AbstractExternalTask.php:31
Stack trace:
#0 [internal function]: GrumPHP\Task\AbstractExternalTask->__construct(Object(GrumPHP\Configuration\GrumPHP))
#1 /Users/anahkiasen/Sites/stappler/aromatech-extranet-reactor/vendor/symfony/dependency-injection/ContainerBuilder.php(900): ReflectionClass->newInstanceArgs(Array)
#2 /Users/anahkiasen/Sites/stappler/aromatech-extranet-reactor/vendor/symfony/dependency-injection/ContainerBuilder.php(451): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'task.git.confli...')
#3 /Users/anahkiasen/Sites/stappler/aromatech-extranet-reactor/vendor/symfony/dependency-injection/ContainerBuilder.php(957): Symfony\Component\DependencyInjection\ContainerBuilder->get('task.git.c in /Users/anahkiasen/Sites/stappler/aromatech-extranet-reactor/vendor/phpro/grumphp/src/Task/AbstractExternalTask.php on line 31

Fatal error: Uncaught ArgumentCountError: Too few arguments to function GrumPHP\Task\AbstractExternalTask::__construct(), 1 passed and exactly 3 expected in /Users/anahkiasen/Sites/stappler/aromatech-extranet-reactor/vendor/phpro/grumphp/src/Task/AbstractExternalTask.php:31
Stack trace:
#0 [internal function]: GrumPHP\Task\AbstractExternalTask->__construct(Object(GrumPHP\Configuration\GrumPHP))
#1 /Users/anahkiasen/Sites/stappler/aromatech-extranet-reactor/vendor/symfony/dependency-injection/ContainerBuilder.php(900): ReflectionClass->newInstanceArgs(Array)
#2 /Users/anahkiasen/Sites/stappler/aromatech-extranet-reactor/vendor/symfony/dependency-injection/ContainerBuilder.php(451): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'task.git.confli...')
#3 /Users/anahkiasen/Sites/stappler/aromatech-extranet-reactor/vendor/symfony/dependency-injection/ContainerBuilder.php(957): Symfony\Component\DependencyInjection\ContainerBuilder->get('task.git.c in /Users/anahkiasen/Sites/stappler/aromatech-extranet-reactor/vendor/phpro/grumphp/src/Task/AbstractExternalTask.php on line 31
```

Removing the task makes the error go away

**Comment by veewee** [comment]
It looks like the internal task config is invalid. It should look something like this:

```yml
services:
    task.git.conflict:
        class: GrumPHP\Task\Git\Conflict
        arguments:
            - '@config'
            - '@process_builder'
            - '@formatter.raw_process'
        tags:
            - {name: grumphp.task, config: git_conflict}
````

Can you validate if this works for you?
