### ISSUE TITLE
hooks_preset: vagrant doesn't execute GrumPHP inside the machine

### ISSUE THREAD

**Issue by poteirard** [phpro/grumphp#362]
| Q               | A
| --------------- | ---
| Version         | 0.11.5
| Bug?            | yes/no
| New feature?    | yes/no
| Question?       | yes
| Documentation?  | yes/no
| Related tickets | .

Hi,

First of all thank you for all this work :)

Is there a way to use GrumPHP inside and outside vagrant? I have a team where there are people who use git inside the vagrant machine and other people who use it from the host machine.

**My configuration**
```yaml
# grumphp.yml
parameters:
    bin_dir: "./src/php/bin"
    git_dir: "."
    hooks_dir: ~
    hooks_preset: vagrant
    stop_on_failure: false
    ignore_unstaged_changes: false
    hide_circumvention_tip: false
    process_async_limit: 10
    process_async_wait: 1000
    process_timeout: 60
    tasks:
        composer: ~
        git_blacklist: ~
        git_commit_message:
            matchers:
                Commit must start with capital letter and end with the JIRA issure number: /[A-Z]{1}.*?\. \#MXB-\d+/
        jsonlint: ~
        npm_script:
            script: test
            triggered_by: [js, vue]
            working_directory: "./src/php/public/phoenix"
            is_run_task: true
        phpcsfixer: ~
        phpcsfixer2: ~
        php_cs_auto_fixer: ~
        php_cs_auto_fixerv2: ~
        phplint: ~
        phpmd: ~
        phpunit:
            config_file: src/php/tests/phpunit.xml
            testsuite: unit
            group: []
            always_execute: false

        xmllint: ~
        yamllint: ~

    testsuites: []
    extensions:
- Wearejust\GrumPHPExtra\Extension\Loader
```

**Steps to reproduce:**
```bash
$ git add -A && git commit -m "Test"
...executing GrumPHP correctly...

$ vagrant ssh
$guest: git add -A && git commit -m "Test"
.git/hooks/pre-commit: 12: .git/hooks/pre-commit: vagrant: not found
```
Maybe we need a hooks_preset like hybrid?
