### ISSUE TITLE
Uncommitted filestate is used

### ISSUE THREAD

**Issue by thisisboris** [phpro/grumphp#365]
| Q               | A
| --------------- | ---
| Version         | `grumphp -V`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | #100, #123 

**My configuration**
```yaml
parameters:
  git_dir: .
  bin_dir: ./vendor/bin
  stop_on_failure: true
  hide_circumvention_tip: true
  tasks:
    composer:
      file: ./composer.json
    phpcs:
      standard: "vendor/magento-ecg/coding-standard/Ecg/"
      ignore_patterns: ['vendor', 'lib', 'core', 'community']
      show_warnings: false
    phplint:
      exclude: ['vendor', 'lib', 'core', 'community']
      jobs: ~
      triggered_by: ['php', 'phtml']
    phpmnd:
      directory: .
      hint: true
      triggered_by: ['php', 'phtml']
      extensions: ['argument','array','operation', 'return', 'condition','switch_case']
    phpmd:
      ruleset: ['cleancode', 'codesize']
      triggered_by: ['php']
    git_blacklist:
      keywords:
          - "die("
          - "var_dump("
          - "exit;"
          - "exec("
          - "shell_exec("
          - "`"
          - "print_r("
      triggered_by: [php]
      regexp_type: G
```

**Steps to reproduce:**

- [ ] Write some invalid code.
- [ ] Try to commit
- [ ] See that commit fails (as expected)
- [ ] Change the invalid code, but do not stage the changes
- [ ] Try to Commit
 
**Result:**
Invalid codestate is still in commit, commit passes all checks. 
GrumPHP does not prevent commit even though no changes to code were added to git.
