### ISSUE TITLE
GrumPHP always happy on Windows; not running tasks

### ISSUE THREAD

**Issue by amcsi** [phpro/grumphp#368]
| Q               | A
| --------------- | ---
| Version         | `GrumPHP 0.11.2`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | n/a

On Windows 10 I have GrumPHP installed supposedly doing 3 different tasks including PHPCS.
Unfortunately although GrumPHP does run on pre-commit, I always get the happy face even if there are clearly style/syntax errors.

**Steps to reproduce:**
```sh
# ... Make blatant style errors.
git commit -a
# Save and exit the editor with an empty commit message.
```

**Expected result**
```
GrumPHP detected a pre-commit command.
GrumPHP is sniffing your code!
Running task 1/3: Composer... ✔
Running task 2/3: PhpCsFixerV2... ✘
Running task 3/3: PhpParser... ✔
             ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
           ▄▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
         ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄
        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
       ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
  ▄███▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 █▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
   ▀█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
     ▀▀▓▓▓▓▓▓▓▓▓▓▓▓█▀▀▀▀▀▀▀▀▀▀▀▀▀▀████████████▄
      ▄███████                       ██████████
     ███████▀  ▀▀▀▀▀▄      ▄▀▀▀▀▀     █████ ▀
      ▐████      ▐██        ▐██        ████▌
      ████▌                            ███
       ▌██▌           ▄▄ ▄▄           ▐███
        ███       ▄▄▄▄▄▄▄▄▄▄▄▄       ▐███
         ██▄ ▐███████████████████████████
        █▀███████████▀     ▀▀███████████
          ██████████▄███████▄███████████
         ▐█████████████████████████████
          █████████████████████████████
           ██ █████████████████████▐██▀
            ▀ ▐███████████████████▌ ▐▀
                ████▀████████▀▐███
                 ▀█▌  ▐█████  ██▌
                        ██▀   ▐▀

       ██████████████████████████████████
       █░░░░░░▀█▀░░░░░░▀█░░░░░░▀█▀░░░░░▀█
       █░░▐█▌░░█░░░██░░░█░░██░░░█░░░██░░█
       █░░▐█▌░░█░░░██░░░█░░██░░░█░░░██░░█
       █░░▐█▌░░█░░░██░░░█░░░░░░▄█░░▄▄▄▄▄█
       █░░▐█▌░░█░░░██░░░█░░░░████░░░░░░░█
       █░░░█░░░█▄░░░░░░▄█░░░░████▄░░░░░▄█
       ██████████████████████████████████

1) init.php (include,no_whitespace_in_blank_line)

You can fix all errors by running following commands:
'/srv/project/vendor/bin/php-cs-fixer' '--allow-risky=yes' '--rules={"@Symfony":true,"array_syntax":{"syntax":"short"},"blank_line_after_opening_tag":false,"blank_line_before_return":false,"cast_spaces":false,"class_definition":{"singleLine":false},"combine_consecutive_unsets":true,"concat_space":{"spacing":"one"},"dir_constant":true,"ereg_to_preg":true,"heredoc_to_nowdoc":true,"linebreak_after_opening_tag":true,"modernize_types_casting":true,"new_with_braces":false,"no_extra_consecutive_blank_lines":["continue","curly_brace_block","extra","parenthesis_brace_block","square_brace_block","throw","use","useTrait"],"no_multiline_whitespace_around_double_arrow":false,"no_php4_constructor":true,"no_unreachable_default_argument_value":true,"no_useless_else":true,"ordered_class_elements":["use_trait","constant","property","construct","destruct","magic","phpunit","method"],"ordered_imports":true,"protected_to_private":true,"psr0":true,"psr4":true,"single_blank_line_before_namespace":false,"strict_comparison":true,"strict_param":true,"php_unit_strict":true,"phpdoc_add_missing_param_annotation":{"only_untyped":false},"phpdoc_align":false,"phpdoc_annotation_without_dot":false,"phpdoc_no_empty_return":false,"phpdoc_separation":false,"phpdoc_summary":false}' '--using-cache=yes' '--verbose' 'fix' 'init.php'
```

**Example result from colleagues when there really are no style errors**
```
GrumPHP detected a pre-commit command.
GrumPHP is sniffing your code!
Running task 1/3: Composer... ✔
Running task 2/3: PhpCsFixerV2... ✔
Running task 3/3: PhpParser... ✔
GrumPHP detected a commit-msg command.
GrumPHP is sniffing your code!
             ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
           ▄▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
         ▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
  ▄▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
   ▀█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
     ▀▀▓▓▓▓▓▓▓▓▓▓▓▓█▀▀▀▀▀▀▀▀▀▀▀▀▀▀████████████▄
      ▄████████▀▀▀▀▀                 ██████████
     ███████▀                         ██████▀
      ▐████      ██▌          ██       ████▌
        ▐█▌                            ███
         █▌           ▄▄ ▄▄           ▐███
        ███       ▄▄▄▄▄▄▄▄▄▄▄▄       ▐███
         ██▄ ▐███████████████████████████
        █▀█████████▌▀▀▀▀▀▀▀▀▀██████████▌▐
          ███████████▄▄▄▄▄▄▄███████████▌
         ▐█████████████████████████████
          █████████████████████████████
           ██ █████████████████████▐██▀
            ▀ ▐███████████████████▌ ▐▀
                ████▀████████▀▐███
                 ▀█▌  ▐█████  ▐█▌
                        ██▀   ▐▀
       _    _ _                         _ _
      / \  | | |   __ _  ___   ___   __| | |
     / _ \ | | |  / _` |/ _ \ / _ \ / _` | |
    / ___ \| | | | (_| | (_) | (_) | (_| |_|
   /_/   \_\_|_|  \__, |\___/ \___/ \__,_(_)
                  |___/
Aborting commit due to empty commit message.
```

**Actual Windows Result whether or not the styles are good**
```
GrumPHP detected a pre-commit command.
GrumPHP is sniffing your code!
GrumPHP detected a commit-msg command.
GrumPHP is sniffing your code!
             ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
           ▄▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
         ▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
  ▄▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
   ▀█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
     ▀▀▓▓▓▓▓▓▓▓▓▓▓▓█▀▀▀▀▀▀▀▀▀▀▀▀▀▀████████████▄
      ▄████████▀▀▀▀▀                 ██████████
     ███████▀                         ██████▀
      ▐████      ██▌          ██       ████▌
        ▐█▌                            ███
         █▌           ▄▄ ▄▄           ▐███
        ███       ▄▄▄▄▄▄▄▄▄▄▄▄       ▐███
         ██▄ ▐███████████████████████████
        █▀█████████▌▀▀▀▀▀▀▀▀▀██████████▌▐
          ███████████▄▄▄▄▄▄▄███████████▌
         ▐█████████████████████████████
          █████████████████████████████
           ██ █████████████████████▐██▀
            ▀ ▐███████████████████▌ ▐▀
                ████▀████████▀▐███
                 ▀█▌  ▐█████  ▐█▌
                        ██▀   ▐▀
       _    _ _                         _ _
      / \  | | |   __ _  ___   ___   __| | |
     / _ \ | | |  / _` |/ _ \ / _ \ / _` | |
    / ___ \| | | | (_| | (_) | (_) | (_| |_|
   /_/   \_\_|_|  \__, |\___/ \___/ \__,_(_)
                  |___/
Aborting commit due to empty commit message.
```

**Comment by veewee** [comment]
Hello @amcsi,

Thanks for reporting!

Can you change the git hook `.git/hooks/pre-commit` so that the -vvv option is added to the grumphp command and show the php-cs-fixer command that is being executed? I think that the changed file is not being validated by php-cs-fixer. Can you also paste your grumphp.yml config file and additional information about your setup?

Does the error only occur on Windows?

**Comment by amcsi** [comment]
@veewee Unfortunately even if I use -vvv the output is the same:

```
GrumPHP detected a commit-msg command.
GrumPHP is sniffing your code!
             ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
           ▄▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
         ▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
  ▄▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
   ▀█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
     ▀▀▓▓▓▓▓▓▓▓▓▓▓▓█▀▀▀▀▀▀▀▀▀▀▀▀▀▀████████████▄
      ▄████████▀▀▀▀▀                 ██████████
     ███████▀                         ██████▀
      ▐████      ██▌          ██       ████▌
        ▐█▌                            ███
         █▌           ▄▄ ▄▄           ▐███
        ███       ▄▄▄▄▄▄▄▄▄▄▄▄       ▐███
         ██▄ ▐███████████████████████████
        █▀█████████▌▀▀▀▀▀▀▀▀▀██████████▌▐
          ███████████▄▄▄▄▄▄▄███████████▌
         ▐█████████████████████████████
          █████████████████████████████
           ██ █████████████████████▐██▀
            ▀ ▐███████████████████▌ ▐▀
                ████▀████████▀▐███
                 ▀█▌  ▐█████  ▐█▌
                        ██▀   ▐▀
       _    _ _                         _ _
      / \  | | |   __ _  ___   ___   __| | |
     / _ \ | | |  / _` |/ _ \ / _ \ / _` | |
    / ___ \| | | | (_| | (_) | (_) | (_| |_|
   /_/   \_\_|_|  \__, |\___/ \___/ \__,_(_)
                  |___/
Aborting commit due to empty commit message.

C:\Users\attila\Vagrant\wa\wa-api>
```

The pre-commit contents is the following:
```
#!/usr/bin/env php
<?php

define('GRUMPHP_PATH', realpath(__DIR__ . '/..'));

$autoloadLocations = [
    getcwd() . '/vendor/autoload.php',
    getcwd() . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../../autoload.php',
];

$loaded = false;
foreach ($autoloadLocations as $autoload) {
    if (is_file($autoload)) {
        require_once($autoload);
        $loaded = true;
    }
}

if (!$loaded) {
    fwrite(STDERR,
        'You must set up the project dependencies, run the following commands:' . PHP_EOL .
        'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    exit(1);
}

$app = new GrumPHP\Console\Application();
$app->run();
```

This only happens on Windows. All my colleagues using mostly Mac, some Linux and actually even for some Windows users there's no problem; only for me using Windows I get this.

My grumphp.yml file is this:

```yaml
parameters:
  tasks:
    composer:

    phpparser:
      visitors:
        no_exit_statements: ~

    phpcsfixer2:
      allow_risky: true
      rules:
        '@Symfony': true

        array_syntax:
          syntax: short
        blank_line_after_opening_tag: false
        blank_line_before_return: false
        cast_spaces: false
        class_definition:
          singleLine: false
        combine_consecutive_unsets: true
        concat_space:
          spacing: one
        declare_strict_types: true
        dir_constant: true
        ereg_to_preg: true
        heredoc_to_nowdoc: true
        linebreak_after_opening_tag: true
        modernize_types_casting: true
        new_with_braces: false
        no_extra_consecutive_blank_lines:
          - continue
          - curly_brace_block
          - extra
          - parenthesis_brace_block
          - square_brace_block
          - throw
          - use
          - useTrait
        no_multiline_whitespace_around_double_arrow: false
        no_php4_constructor: true
        no_unreachable_default_argument_value: true
        no_useless_else: true
        ordered_class_elements:
          - use_trait
          - constant
          - property
          - construct
          - destruct
          - magic
          - phpunit
          - method
        ordered_imports: true
        protected_to_private: true
        psr0: true
        psr4: true
        single_blank_line_before_namespace: false
        strict_comparison: true
        strict_param: true
        ternary_to_null_coalescing: true

        # PHPUnit
        php_unit_strict: true

        # PHPDoc
        phpdoc_add_missing_param_annotation:
          only_untyped: false
        phpdoc_align: false
        phpdoc_annotation_without_dot: false
        phpdoc_no_empty_return: false
        phpdoc_separation: false
        phpdoc_summary: false
```
