### ISSUE TITLE
The executable for "parallel-lint" could not be found. how to resolve this 

### ISSUE THREAD

**Issue by yatinPatel13490** [phpro/grumphp#370]
| Q               | A
| --------------- | ---
| Version         | `0.9.6`
| Bug?            | yes
| New feature?    | yes/no
| Question?       | yes/no
| Documentation?  | yes/no
| Related tickets | it gives me an error

**My configuration**
```yaml
# grumphp.yml
parameters:
    git_dir: .
    bin_dir: vendor/bin
    tasks:
      phplint:
          exclude: []
          triggered_by: ['php', 'phtml', 'php3', 'php4', 'php5']
```

**Steps to reproduce:**
```sh
# Generate empty folder
mkdir tmp
cd tmp
git init
echo "vendor" > .gitignore
pbpaste > grumphp.yml
composer require --dev phpro/grumphp

# Your actions
I remove the semicolon and get the red images but not get any description reagarding to php error 
and get the error like :
The executable for "parallel-lint" could not be found.
# Please add the steps on how to reproduce the issue here.

# Run GrumpHP:
git add -A && git commit -m"Test"
# or
./vendor/bin/grumphp run
```

**Result:**
```
The executable for "parallel-lint" could not be found.
# Please add the result of the run or git commit actions here.
```
