### ISSUE TITLE
Check phpstan errors for all files, not only for the commited ones

### ISSUE THREAD

**Issue by wagnerferreirasp** [phpro/grumphp#393]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 0.11.6
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

**My configuration**

```yaml
# grumphp.yml
parameters:
    git_dir: .
    bin_dir: vendor/bin
    tasks:     
        phpstan:
            autoload_file: ~
            configuration: "./config/phpstan.neon"
            level: 5
            triggered_by: ['php']
```

**Steps to reproduce:**

# Your actions
1. Change a method signature of class A, forcing an error that phpstan catches on other classes.
2. Commit the class A successfully

# Run GrumpHP:
```
./vendor/bin/grumphp run
```

**Result:**
The run shows erros for files that were not changed, but uses the method of class A that changed.
However, the commit was "All good", probably because the commited file has no errors, but the other were affected by the change of class A.
