### ISSUE TITLE
Despite errors on file, GrumPHP allows file to be commited

### ISSUE THREAD

**Issue by naknode** [phpro/grumphp#402]
| Q               | A
| --------------- | ---
| Version         | `0.12.0`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

**My configuration**
```yaml
parameters:
    git_dir: .
    bin_dir: vendor/bin
    tasks:
      phpcs:
        standard: PSR2
        ignore_patterns: [./public, ./tests, ./resources, ./database, ./bootstrap]

```

**Steps to reproduce:**
```sh
# Generate empty folder
mkdir tmp
cd tmp
git init
echo "vendor" > .gitignore
pbpaste > grumphp.yml
composer require --dev phpro/grumphp

# Your actions
# Please add the steps on how to reproduce the issue here.

1. `laravel new cq`
2. `cd cq`
3. `php artisan serve`

Then I go to a file like `User.php` and add a realy, really long array to make it error.

Running `vendor\bin\grumphp run` will give the GrumPHP red error as expected.

# Run GrumpHP:
git add -A && git commit -m"Test"
# or
./vendor/bin/grumphp run
```

**Result:**

But when I do `git add -A && git commit -m "Test."`,

I get: 

```
λ git add -A && git commit -m "Other."
warning: LF will be replaced by CRLF in app/Http/Controllers/Controller.php.
The file will have its original line endings in your working directory.
[master 7a5e64c] Other.
 1 file changed, 1 insertion(+), 1 deletion(-
```

This is on a **fresh** install of a Laravel 5.5 project. Windows 10.
