### ISSUE TITLE
max_body_width setting of git task also is applied to commented lines

### ISSUE THREAD

**Issue by schmengler** [phpro/grumphp#406]
| Q               | A
| --------------- | ---
| Version         | 0.12.0
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

The `max_body_witdth` check for git commit messages should exclude lines starting with `#`. These are comments that do not end up in the commit and often are automatically generated with long lines, for example in merge commits or with a localized git installation.

**My configuration**
```yaml
# grumphp.yml
parameters:
    tasks:
        git_commit_message:
            max_subject_width: 80
            max_body_width: 80
```

**Steps to reproduce:**
```sh
# Generate empty folder
mkdir tmp
cd tmp
git init
echo "vendor" > .gitignore
pbpaste > grumphp.yml
composer require --dev phpro/grumphp

# Your actions

git commit --allow-empty -m "Test

# this looks like a long line, but it won't actually end up in the commit. I am writing random stuff now to reach the limit. Knowledge is power, France is bacon.
"
```

**Result:**
```
Line 3 of commit message has > 80 characters.
```
