### ISSUE TITLE
enforce_single_lined_subject raises error when message is one line

### ISSUE THREAD

**Issue by glamorous** [phpro/grumphp#413]
| Q               | A
| --------------- | ---
| Version         | `0.12.0`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

**My configuration**
```yaml
parameters:
    git_dir: .
    bin_dir: vendor/bin
    tasks:
      composer: ~
      git_commit_message:
        enforce_capitalized_subject: false
        max_subject_width: 72
        matchers:
          - /^(bugfix|feature|refactor|cleanup|typo|other|test|doc|release|sync|staging) - /
```

**Steps to reproduce:**
```sh
# Prepare new commit in bash
touch test.txt
git commit
# bash "opens window" to add git commit message
# you add:
other - test of my commits works

# There is no blank line, only commits
# GrumpHP has runned and gives the `enforce_single_lined_subject ` error
```

**Result:**
```
Subject should be one line and followed by a blank line.
```

If you commit through `git commit -am 'other - here is my message'` there is no such error. Not logical that this check run if you commit message is only one line and not multiline. It should only check for the blank lines if more then one line is given.
