### ISSUE TITLE
TypeError: Argument 6 passed to Symfony\Component\Process\Process::__construct() must be of the type array, null given

### ISSUE THREAD

**Issue by alexgiuvara** [phpro/grumphp#414]
| Q               | A
| --------------- | ---
| Version         | 0.12.0
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | #342

**My configuration**
```yaml
# grumphp.yml
parameters:
    git_dir: .
    bin_dir: vendor/bin
    tasks:
        phpmd:
            exclude:
            - tests/
            - helpers.php
            ruleset: ['/config/phpmd/custom.xml']
            triggered_by: ['php']
        phplint:
            exclude: []
            jobs: ~
            triggered_by: ['php']
        phpcsfixer:
            config_file: .php_cs
            config: ~
            fixers: []
            level: ~
            verbose: true
        phpunit:
            config_file: ~
            group: []
            always_execute: true
        phpspec:
            config_file: ~
            format: ~
            stop_on_failure: false
            verbose: false
```

**Steps to reproduce:**
This error occurs when I require GrumPHP in a Laravel 5.5 project. It works in Lumen 5.5.1
```sh
# Install GrumpHP:
composer require --dev phpro/grumphp
```

**Result:**
```
PHP Fatal error:  Uncaught TypeError: Argument 6 passed to Symfony\Component\Process\Process::__construct() must be of the type array, null given, called in /home/vagrant/Code/laravel/vendor/symfony/process/ProcessBuilder.php on line 270 and defined in phar:///usr/local/bin/composer/vendor/symfony/process/Process.php:141
Stack trace:
#0 /home/vagrant/Code/laravel/vendor/symfony/process/ProcessBuilder.php(270): Symfony\Component\Process\Process->__construct(Array, NULL, Array, NULL, 60, NULL)
#1 /home/vagrant/Code/laravel/vendor/phpro/grumphp/src/Composer/GrumPHPPlugin.php(182): Symfony\Component\Process\ProcessBuilder->getProcess()
#2 /home/vagrant/Code/laravel/vendor/phpro/grumphp/src/Composer/GrumPHPPlugin.php(137): GrumPHP\Composer\GrumPHPPlugin->runGrumPhpCommand('configure')
#3 [internal function]: GrumPHP\Composer\GrumPHPPlugin->runScheduledTasks(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(171): call_user_func(Array, Object(Composer\Script\Event))
#5 phar:///u in phar:///usr/local/bin/composer/vendor/symfony/process/Process.php on line 141

```
