### ISSUE TITLE
PhpCsFixerFormatter - escapeArgument

### ISSUE THREAD

**Issue by arnaud-large** [phpro/grumphp#446]
| Q               | A
| --------------- | ---
| Version         | 0.13.0
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

**My configuration**
```yaml
parameters:
    git_dir: .
    bin_dir: vendor/bin
    tasks:
        phplint: ~
        phpcsfixer: ~
    ascii:
        failed: ~
        succeeded: ~
```

**Steps to reproduce:**
```sh
# Generate empty folder
mkdir tmp
cd tmp
git init
echo "vendor" > .gitignore
pbpaste > grumphp.yml
composer require --dev phpro/grumphp

# Your actions
# Please add the steps on how to reproduce the issue here.

# Run GrumpHP:
git add -A && git commit -m"Test"
# or
./vendor/bin/grumphp run
```

**Result:**
```
Running task 1/2: PhpCsFixer... PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Process\ProcessUtils::escapeArgument() in /vendor/phpro/grumphp/src/Formatter/PhpCsFixerFormatter.php:51
```
If i have a psr error in a php file this error occures when commiting. I think this is a namespace issue. It should use the class in grumphp/src/Process instead of the symfony one.
