### ISSUE TITLE
Task phpcs can not set config warning_severity to 0

### ISSUE THREAD

**Issue by Kanti** [phpro/grumphp#466]
| Q               | A
| --------------- | ---
| Version         | 0.13.1
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | -

If I set warning_severity to 0 in my grumphp.yml than the argument --warning-severity is not given to the phpcs command.

```yaml
parameters:
  tasks:
    phpcs:
      standard: "PSR2"
      warning_severity: 0
      tab_width: 4
```
Or with this Config:
```yaml
parameters:
  tasks:
    phpcs:
      standard: "PSR2"
      warning_severity: "0"
      tab_width: 4
```
Result: Error: The option "warning_severity" with value "0" is expected to be of type "null" or "int", but is of type "string".

**Steps to reproduce:**
```sh
mkdir tmp
cd tmp
git init
echo "vendor" > .gitignore
pbpaste > grumphp.yml
composer require --dev phpro/grumphp

# Run GrumpHP:
./vendor/bin/grumphp run
```
