### ISSUE TITLE
PhpCpd "names_exclude" option doesn't work

### ISSUE THREAD

**Issue by vyshkant** [phpro/grumphp#475]
| Q               | A
| --------------- | ---
| Version         | `GrumPHP 0.14.0`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | #277

**My configuration**
```yaml
# grumphp.yml
parameters:
    tasks:
        phpcpd:
            names_exclude:
              - 'Foo.php'
              - 'Bar.php'
```

I skip the "steps to reproduce" and the "expected results", because this bug can be seen with the naked eye.

I'm talking about the format of the `names_exclude` (`names-exclude`) option passed to the phpcpd.

https://github.com/phpro/grumphp/blob/b5d547def4ea08bd8aa0e43f1130c5936ace621b/src/Task/PhpCpd.php#L77

As we can see, we're trying to pass this option using `addArgumentArray` method, which means that it will be formatted as
`--names-exclude=Foo.php --names-exclude=Bar.php`.

In the same time `phpcpd` expects this option to not be an array and to have comma-separated value:

https://github.com/sebastianbergmann/phpcpd/blob/24d9a880deadb0b8c9680e9cfe78e30b704225db/src/CLI/Command.php#L55-L61

I'm going to create a PR that replaces the call of `addArgumentArray` method with the call of `addOptionalCommaSeparatedArgument` method.
