### ISSUE TITLE
Imported config gets overwritten not customized

### ISSUE THREAD

**Issue by thomscode** [phpro/grumphp#480]
| Q               | A
| --------------- | ---
| Version         | 0.14.0
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | no

My company develops and hosts several Drupal sites, which we are starting to manage with Composer. To help with checking files, I setup a base GrumPHP configuration to share across projects and am using the `imports` key to import that into the project so I can continue to customize the settings as projects have need to do so. I set this up per the "convention" instructions in the [Docs](https://github.com/phpro/grumphp/blob/master/doc/conventions.md#customizable-conventions)

The shared configuration contains task settings. If I try to overwrite the settings for any given task, GrumPHP overwrites the entire `tasks` key (possibly `parameters` too).

**My shared configuration**
```yaml
# grumphp.yml
parameters:
  tasks:
    composer: ~
    file_size: ~
    phpcs:
      standard: vendor/drupal/coder/coder_sniffer/Drupal
      triggered_by: ["php", "module", "profile", "theme", "inc"]
    phplint:
      triggered_by: ["php", "module", "profile", "theme", "inc"]
    phpmd:
      triggered_by: ["php", "module", "profile", "theme", "inc"]
    phpparser:
      kind: php5
      triggered_by: ["php", "module", "profile", "theme", "inc"]
    phpversion:
      project: "5.6"
    securitychecker: ~
```
**My configuration**
```yaml
# grumphp.yml
imports:
  - resource: my/other/shared/grumphp.yml
parameters:
  tasks:
    jsonlint: ~
    yamllint:~
```

**Steps to reproduce:**
* Create the first "shared" `grumphp.yml` file
* Import that into your main `grumphp.yml` file (import part of second config above)
* Run GrumPHP; `grumphp run`
    * **Result:** All tasks in shared config will run
* Add `jsonlint` and `yamllint` tasks to main `grumphp.yml` file
* Run GrumPHP: `grumphp run`
    * **Result:** Only `jsonlint` and `yamllint` tasks run

**Expected:**
I would have expected that the two configurations would have been merged and not that the second would overwrite the first.
