### ISSUE TITLE
PHPStan ignore_patterns only works on specific files

### ISSUE THREAD

**Issue by cdekok** [phpro/grumphp#493]
| Q               | A
| --------------- | ---
| Version         | `GrumPHP 0.14.0`
| Bug?            | yes

**My configuration**
```
parameters:
    git_dir: .
    bin_dir: vendor/bin
    tasks:
        phpunit:
            config_file: ~
            testsuite: ~
            group: []
            always_execute: false
        phpstan:
            autoload_file: ~
            configuration: ~
            level: 0
            force_patterns: []
            ignore_patterns: ['MCPClientScripts/*.php']
            triggered_by: ['php']
        phpcs:
            standard: PSR2
            ignore_patterns:
            - "MCPClientScripts/*.php"
```

**Steps to reproduce:**
Edit a file under MCPClientScripts
And it will still run the file through phpstan if I add the specific file to patterns it is ignored correctly.
