### ISSUE TITLE
Multiple configuration files with local overriding

### ISSUE THREAD

**Issue by mgeoffray** [phpro/grumphp#499]
| Q               | A
| --------------- | ---
| Version         |
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | 
| Related tickets | comma-separated list of related tickets

Hi,
I would like to know if it is possible to have multiple config files?

Multiple projects with the same grumphp.yml configuration file but I would like to make a project specific config file overriding the default one.

Something like that:

**Project A / Project B / Project C** have the same config file
`grumphp.yml`
```yaml
parameters:
    stop_on_failure: true
    ascii:
        failed: ~
        succeeded: ~
    tasks:
        git_blacklist:
            keywords:
                - "die;"
            triggered_by: [php]
```

I would like to change config for Project A
`grumphp.local.yml`
```yaml
parameters:
    tasks:
        git_blacklist:
            keywords:
                - "die;"
                - "var_dump"
```

The idea behind this is to have a common configuration for all project with the possibility to override configuration project by project with a second file, for example `grumphp.local.yml`
