### ISSUE TITLE
Phan doesn't work, although the result show "Running task 1/3: Phan... ✔".

### ISSUE THREAD

**Issue by khadgarmage** [phpro/grumphp#518]
| Q               | A
| --------------- | ---
| Version         | 0.14.1
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

Phan not work, although the result show "Running task 1/3: Phan... ✔".

**My configuration**
* yaml config
```yaml
parameters:
    git_dir: .
    bin_dir: vendor/bin
    tasks:
        phpstan:
            autoload_file: ./public/classload.php
            configuration: ~
            level: 0
            force_patterns: []
            ignore_patterns: []
            triggered_by: [php]
        securitychecker: ~
        phan:
            config_file: .phan/config.php
            output_mode: text
            output: null
            triggered_by: [php]
```
* phan config
``` phan config
return [
    "allow_missing_properties" => true,
    "null_casts_as_any_type" => true,
    'backward_compatibility_checks' => false,
    "quick_mode" => true,
    "minimum_severity" => 10,
    'parent_constructor_required' => [
    ],
    "exclude_analysis_directory_list" => [
    ],
];
```

**Steps to reproduce:**
```sh
git commit -m "Test"
```

**Result:**
Phan doesn't work, the phpstan is ok.
```
~/Work/ffs/code(php7 ✗) git commit -am 'team'
GrumPHP detected a pre-commit command.
GrumPHP is sniffing your code!
Running task 1/3: Phan... ✔
Running task 2/3: PhpStan... ✘
Running task 3/3: SecurityChecker... ✔
------ ------------------------------------------------------------------------
  Line   mongopetteam.php
 ------ ------------------------------------------------------------------------
  48     Class Ko referenced with incorrect case: ko.
  54     Access to an undefined property MongopetteamModel::$intLastTeamId.
  66     Access to an undefined property MongopetteamModel::$arrProfiles.
  292    Call to static method inst() on an unknown class
         Models\UserShareInfoModel.
  421    Access to an undefined property MongopetteamModel::$arrProfiles.
  661    Method MongopetteamModel::delBusyPet() invoked with 2 parameters, 1
         required.
  682    Method MongopetteamModel::delBusyPet() invoked with 2 parameters, 1
         required.
  829    Access to an undefined property MongopetteamModel::$arrProfiles.
  833    Access to an undefined property MongopetteamModel::$arrProfiles.
  988    Call to static method inst() on an unknown class Models\NeighborModel.
  1165   Access to an undefined property MongopetteamModel::$intLastTeamId.
  1218   Access to an undefined property MongopetteamModel::$intLastTeamId.
  1223   Access to an undefined property MongopetteamModel::$intLastTeamId.
  1230   Access to an undefined property MongopetteamModel::$intLastTeamId.
  1282   Access to an undefined property MongopetteamModel::$arrProfiles.
  1285   Access to an undefined property MongopetteamModel::$intLastTeamId.
 ------ ------------------------------------------------------------------------

 [ERROR] Found 16 errors
```

I run phan, the result show as followed:
```
~/Work/ffs/code(php7 ✗) ./vendor/bin/phan application/models/mongopet.php
application/models/mongopet.php:2 PhanUndeclaredExtendedClass Class extends undeclared class \Mongomodel
application/models/mongopet.php:114 PhanUndeclaredClass Reference to undeclared class \Mongomodel
application/models/mongopet.php:116 PhanUndeclaredClassMethod Call to method commonConfig from undeclared class \Tools
application/models/mongopet.php:117 PhanUndeclaredClassMethod Call to method commonConfig from undeclared class \Tools
application/models/mongopet.php:118 PhanUndeclaredClassMethod Call to method commonConfig from undeclared class \Tools
application/models/mongopet.php:119 PhanUndeclaredClassMethod Call to method commonConfig from undeclared class \Tools
application/models/mongopet.php:120 PhanUndeclaredClassMethod Call to method commonConfig from undeclared class \Tools
application/models/mongopet.php:121 PhanUndeclaredClassMethod Call to method commonConfig from undeclared class \Tools
```
