### ISSUE TITLE
yamllint specific directory only

### ISSUE THREAD

**Issue by DidYoun** [phpro/grumphp#527]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 0.14.1
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | [#158](https://github.com/phpro/grumphp/issues/158)

As it's described in the related issue : [158](https://github.com/phpro/grumphp/issues/158), it could be great if we're able to define whitelist paths for the task.

In accordation with the other task which include the whitelist_pattern and the modification made by @mgeoffray, we would have somethink like that :
```yaml
# grumphp.yml
      yamllint:
            ignore_patterns: []
            object_support: false
            exception_on_invalid_type: false
            parse_constant: false
            parse_custom_tags: false
            whitelist_patterns: "/^src\/App\/Bundle\/(.*)/"
```
Because I run GrumPHP on a Symfony project, its take too much times to define all the directories to be ignored. 

Thanks !
