### ISSUE TITLE
TypeError on grumphp git:init

### ISSUE THREAD

**Issue by SerkanYildiz** [phpro/grumphp#550]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 0.14.2
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no

While using branch `dev-grumpy-seventies` you'll end up a TypeError thrown by php. This is because the hooks_dir parameter which is by default null but expects to be a string in Configuration/GrumPHP.php on line 38.

**My configuration**
```yaml
# grumphp.yml
parameters:
  bin_dir: bin
  hooks_dir: ~
  exclude_paths:
      - "bin/"
      - "config/"
      - "spec/"
      - "tests/"
      - "var/"
      - "vendor/"
      - "public/"
  tasks:
    phpcsfixer2:
      allow_risky: true
      config: .php_cs.dist
      config_contains_finder: true
      metadata:
        priority: 500
    phpspec:
      format: pretty
      metadata:
        priority: 400
    composer:
      metadata:
        priority: 51
    infection:
      ignore_patterns: "%exclude_paths%"
      threads: 4
      test_framework: phpspec
      only_covered: true
      min_msi: 100
      min_covered_msi: 100
      metadata:
        priority: 50
        blocking: false
    yamllint:
      parse_custom_tags: true
    file_size: ~
```

**Steps to reproduce:**
```sh
# install "dev-grumpy-seventies"

# Initialize grumphp
bin/grumphp git:init
```

**Result:**
```
PHP Fatal error:  Uncaught TypeError: Return value of GrumPHP\Configuration\GrumPHP::getHooksDir() must be of the type string, null returned in /app/vendor/phpro/grumphp/src/Configuration/GrumPHP.php:38
Stack trace:
#0 /app/vendor/phpro/grumphp/src/Console/Command/Git/InitCommand.php(79): GrumPHP\Configuration\GrumPHP->getHooksDir()
#1 /app/vendor/symfony/console/Command/Command.php(255): GrumPHP\Console\Command\Git\InitCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /app/vendor/symfony/console/Application.php(904): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /app/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(GrumPHP\Console\Command\Git\InitCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /app/vendor/symfony/con in /app/vendor/phpro/grumphp/src/Configuration/GrumPHP.php on line 38
```
