### ISSUE TITLE
[RFC] Improve PhpStan paths configuration

### ISSUE THREAD

**Issue by Th3Mouk** [phpro/grumphp#568]
Hello !

I have currently a DX issue with the paths configuration of the PhpStan task.

Here my current configuration
```
# phpstan.neon
parameters:
    level: 7 
    paths: ['src']

```

But Grum is taking the whole tree structure instead of only `/src`

It's because of this line :
https://github.com/phpro/grumphp/blob/ef7af590f27a1a3144651da239c2338e2d5834d2/src/Task/PhpStan.php#L87

The only ugly workaround currently is:

```yaml
# grumphp.yml
parameters:
    git_dir: .
    bin_dir: vendor/bin
    tasks:
        phpstan:
            level: 7
            ignore_patterns: ['/^(?!src).*/']
```

Before start coding and open a PR, I would like to debate on the best way to improve path configuration.
