### ISSUE TITLE
Text indentation missing?

### ISSUE THREAD

**Issue by ChrisButterworth** [phpro/grumphp#590]
| Q               | A
| --------------- | ---
| Version         | 0.14.3
| Bug?            | Maybe
| New feature?    | no
| Question?       | yes
| Documentation?  | yes

Is there a way to get GrumPHP to test indentation?

Happy with all the other errors and warning but this one seems to be completely missing; here's my configuration in case anything is missing

```yaml
parameters:
    git_dir: .
    bin_dir: _dev/vendor/bin
    tasks:
      phpcs:
        standard: PSR2
        tab_width: 4
        severity: 1
        warning_severity: 1
        triggered_by: [php]
```
