### ISSUE TITLE
Phpstan task: `level` parameter always overwrites configured level in `phpstan.neon`

### ISSUE THREAD

**Issue by prilka** [phpro/grumphp#593]
| Q               | A
| --------------- | ---
| Version         | `GrumPHP 0.14.3`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

The `level` parameter of the Phpstan task always(!) overwrites the configured level in my `phpstan.neon`. That is because the task always/unconditional sets the `--level` command-line option. If I omit the `level` parameter in my `grumphp.yml`, the default value (level 0) is set and my configured level (e.g. level 3) is ignored.

To fix this, I have to set the value in my `grumphp.yml` to the same value as in my `phpstan.neon`, which is annoying. 

While the default value may fit well for most situations, it's inconvenient for this case. So maybe we need some kind of marker to tell the task not to include the `--level` option for the command-line. Something like `level: null` or `level: "unset"`

**My configuration**
```yaml
parameters:
    git_dir: .
    bin_dir: vendor/bin
    tasks:
      ...
      phpstan:
        triggered_by: ['php']
```

**phpstan.neon**
```yaml
parameters:
    level: 3
    ...
```
