### ISSUE TITLE
Possible to have MND run only on changed files?

### ISSUE THREAD

**Issue by MarkVaughn** [phpro/grumphp#622]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 0.15.0
| Bug?            | maybe
| New feature?    | no
| Question?       | yes
| Documentation?  | maybe

**My configuration**
```yaml
parameters:
  git_dir: .
  bin_dir: vendor/bin
  hooks_dir: ~
  hooks_preset: local
  stop_on_failure: true
  tasks:
    phpcs: ~
    phplint: ~
    phpmd: ~
    phpmnd: ~
    phpparser: ~
    phpstan: ~
    securitychecker: ~

```

**Steps to reproduce:**
```sh
# add grumphp to a project with hundreds of magic numbers
# modify a single php file

# Run GrumpHP:
git add -A && git commit -m"Test"
# or
./vendor/bin/grumphp run
```

**Result:**
```
Total of Magic Numbers: 34
Time: 547 ms, Memory: 22.00 MB
```

It seems all other tasks only run on the changed files, but MND runs on the whole project. Is this intentional or an oversight?
