### ISSUE TITLE
Add detect_key_conflicts to yamllint to allow for duplicate keys

### ISSUE THREAD

**Issue by verbruggenalex** [phpro/grumphp#647]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 0.15.2
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | 

This is a feature request to add the `detect_key_conflicts` option like grumphp provides for jsonlint: https://github.com/phpro/grumphp/blob/master/doc/tasks/jsonlint.md#jsonlint. This is required for yaml files like in Drone CI where you are allowed to define duplicate keys. See yaml example in bottom of description.

**My configuration**
```yaml
# grumphp.yml
parameters:
    git_dir: .
    bin_dir: vendor/bin
    tasks:
        yamllint: ~
```

**Steps to reproduce:**
```sh
# Run grumphp
./vendor/bin/grumphp run
```

**Result:**
```
[ERROR] Duplicate key "git" detected in ".drone.yml" at line 11.
```

**Yaml file:**
```yaml
workspace:
  base: /test
  path: drone

clone:
  git:
    image: plugins/git
    recursive: true
    when:
      event: [ push, pull_request, tag ]
  git:
    image: fpfis/true
    when:
      event: [ deployment ]
```
