### ISSUE TITLE
Support request: when creating extension, how do you add command with 2 spaces - "--runtime-set testVersion 7.3"

### ISSUE THREAD

**Issue by hkirsman** [phpro/grumphp#664]
phpcs https://packagist.org/packages/phpcompatibility/php-compatibility package has parameter to change PHP version:

    --runtime-set testVersion 7.3

7.3 is PHP version which is the variable I would like to change.

It could also be like

    --runtime-set testVersion 5.3-5.5

or 

    --runtime-set testVersion 5.3-

My yml file would look something like this:
````yml
parameters:
    git_dir: .
    bin_dir: vendor/bin
    tasks:
        php_compatibility:
            extensions:  [php, inc, module, install]
            testVersion: 7.3
    extensions:
        - hkirsman\PhpCompatibilityTask\ExtensionLoader
````

This is my work so far:
https://github.com/hkirsman/grumphp-php-compatibility/blob/master/src/PhpCompatibilityTask.php

How would you make it work?

Thank you!
