### ISSUE TITLE
With 0.16 getting "The executable for "composer" could not be found" during composer task

### ISSUE THREAD

**Issue by jaydiablo** [phpro/grumphp#671]
| Q               | A
| --------------- | ---
| Version         | `0.16.0`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

Seems that composer executable can't be found by 0.16 (this worked fine in 0.15), so when executing the composer task in grumphp, an error message is shown.

**My configuration**
```yaml
# grumphp.yml
parameters:
    tasks:
        composer:
            strict: true
        composer_require_checker: ~
        phpcsfixer2:
            allow_risky: true
            config: .php_cs
        phpstan:
            level: 7
            configuration: phpstan.neon
        phpunit:
            metadata:
                priority: 100
            always_execute: true
```

**Steps to reproduce:**
```sh
git clone git@github.com:diablomedia/zf1-acl.git
git checkout dependabot/composer/phpro/grumphp-tw-0.14.0or-tw-0.16.0
composer update

# Your actions
./vendor/bin/grumphp run
```

**Result:**
```
GrumPHP is sniffing your code!
Running task 1/5: Phpunit... ✔
Running task 2/5: Composer... ✘
Running task 3/5: ComposerRequireChecker... ✔
Running task 4/5: PhpCsFixerV2... ✔
Running task 5/5: PhpStan... ✔
             ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
           ▄▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
         ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄
        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
       ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
  ▄███▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 █▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
   ▀█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
     ▀▀▓▓▓▓▓▓▓▓▓▓▓▓█▀▀▀▀▀▀▀▀▀▀▀▀▀▀████████████▄
      ▄███████                       ██████████
     ███████▀  ▀▀▀▀▀▄      ▄▀▀▀▀▀     █████ ▀
      ▐████      ▐██        ▐██        ████▌
      ████▌                            ███
       ▌██▌           ▄▄ ▄▄           ▐███
        ███       ▄▄▄▄▄▄▄▄▄▄▄▄       ▐███
         ██▄ ▐███████████████████████████
        █▀███████████▀     ▀▀███████████
          ██████████▄███████▄███████████
         ▐█████████████████████████████
          █████████████████████████████
           ██ █████████████████████▐██▀
            ▀ ▐███████████████████▌ ▐▀
                ████▀████████▀▐███
                 ▀█▌  ▐█████  ██▌
                        ██▀   ▐▀

       ██████████████████████████████████
       █░░░░░░▀█▀░░░░░░▀█░░░░░░▀█▀░░░░░▀█
       █░░▐█▌░░█░░░██░░░█░░██░░░█░░░██░░█
       █░░▐█▌░░█░░░██░░░█░░██░░░█░░░██░░█
       █░░▐█▌░░█░░░██░░░█░░░░░░▄█░░▄▄▄▄▄█
       █░░▐█▌░░█░░░██░░░█░░░░████░░░░░░░█
       █░░░█░░░█▄░░░░░░▄█░░░░████▄░░░░░▄█
       ██████████████████████████████████

The executable for "composer" could not be found.
```

Downgrading this particular repo to 0.15 doesn't have the issue.

Composer is installed globally on this system in `/usr/local/bin/composer.phar` and then aliased to `composer` in `.bash_profile` file.
