### ISSUE TITLE
phplint task doesn't work as excepted

### ISSUE THREAD

**Issue by adrientiburce** [phpro/grumphp#689]
| Q               | A
| --------------- | ---
| Version         | `grumphp -V`
| Bug?            | yes
| New feature?    | no
| Question?       | yes

**My configuration**
```yaml
# grumphp.yml
parameters:
  bin_dir: "./vendor/bin"
  git_dir: "."
  tasks:
    phplint:
      exclude: ['vendor']
      jobs: ~
    phpcsfixer: ~
```

## Issue : I would like to launch php parallel lint but it doesn't work.
When I manualy run **parallel lint**  from terminal with 
` ./vendor/bin/parallel-lint --exclude vendor ` 
I get some errors, but when I commit grumphp enable me to commit 

Is there something I need to change in my `grumphp.yml` ?
