### ISSUE TITLE
Can multiple directories be passed to phpcpd task?

### ISSUE THREAD

**Issue by steigenTI** [phpro/grumphp#696]
I'm using version `0.14.3` of grumphp.

I'm wondering if it's possible to pass multiple directories to the phpcpd task.

My task is configured as follows:
```
tasks:
  phpcpd:
    directory: src/foo src/bar
    triggered_by:
      - php
```

But when I run grumphp, I get the following result: 
```
The "src/foo src/bar" directory does not exist.
```

When I execute the following command via the command line, it correctly checks both directories:
```
vendor/sebastian/phpcpd/phpcpd src/foo src/bar
```
