### ISSUE TITLE
GrumPHP marks all files as removed on partial staging and commit

### ISSUE THREAD

**Issue by Rohaq** [phpro/grumphp#698]
| Q               | A
| --------------- | ---
| Version         | `GrumPHP 0.15.2`
| Git Version | `git version 2.24.0.windows.2`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

**My configuration**

```yaml
# grumphp.yml
parameters:
  bin_dir: vendor/bin
  stop_on_failure: false
  process_timeout: 60
  ignore_unstaged_changes: true
  tasks:
    phpversion:
      project: "7.3"
    composer:
      no_check_all: true
      no_local_repository: true
    securitychecker: ~
    phplint:
      exclude: ["vendor"]
    jsonlint: ~
    phpparser:
      ignore_patterns: ["vendor"]
      visitors:
        forbidden_function_calls:
          blacklist:
            - "var_dump"
            - "phpinfo"
```

**Steps to reproduce:**
1. Make changes to a file in a repository.
2. Choose to stage only a few lines from that file (in a GUI based client, or via CLI) - in my case, it was two changed lines, only a few lines apart, where someone had used `+=` operators where they should have use `.=`
3. Commit these changed lines.
4. GrumPHP runs its pre-commit checks, stashing the unstaged changes beforehand.
5. After the checks have completed GrumPHP restores the stash.
6. Checking the status of the repository, the commit made has removed all of the files, and they appear unstaged in the working copy.

After resetting to the previous commit, I re-ran the same commit with `--no-verify` to avoid running GrumPHP as part of the process, and the issue doesn't occur.

Staging and committing entire files while running GrumPHP doesn't seem to cause the same issue

**Result:**
```
GrumPHP detected a pre-commit command.
Detected unstaged changes... Stashing them!
GrumPHP is sniffing your code!
Running task 1/6: Composer... ✔
Running task 2/6: JsonLint... ✔
Running task 3/6: PhpLint... ✔
Running task 4/6: PhpParser... ✔
Running task 5/6: PhpVersion... ✔
Running task 6/6: SecurityChecker... ✔
Reapplying unstaged changes from stash.
GrumPHP detected a commit-msg command.
GrumPHP is sniffing your code!
             ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
           ▄▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
         ▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
        ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
  ▄▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 ▐▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
 ▐█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
   ▀█▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▌
     ▀▀▓▓▓▓▓▓▓▓▓▓▓▓█▀▀▀▀▀▀▀▀▀▀▀▀▀▀████████████▄
      ▄████████▀▀▀▀▀                 ██████████
     ███████▀                         ██████▀
      ▐████      ██▌          ██       ████▌
        ▐█▌                            ███
         █▌           ▄▄ ▄▄           ▐███
        ███       ▄▄▄▄▄▄▄▄▄▄▄▄       ▐███
         ██▄ ▐███████████████████████████
        █▀█████████▌▀▀▀▀▀▀▀▀▀██████████▌▐
          ███████████▄▄▄▄▄▄▄███████████▌
         ▐█████████████████████████████
          █████████████████████████████
           ██ █████████████████████▐██▀
            ▀ ▐███████████████████▌ ▐▀
                ████▀████████▀▐███
                 ▀█▌  ▐█████  ▐█▌
                        ██▀   ▐▀
       _    _ _                         _ _
      / \  | | |   __ _  ___   ___   __| | |
     / _ \ | | |  / _` |/ _ \ / _ \ / _` | |
    / ___ \| | | | (_| | (_) | (_) | (_| |_|
   /_/   \_\_|_|  \__, |\___/ \___/ \__,_(_)
                  |___/
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
Enumerating objects: 298, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), done.
Total 1 (delta 0), reused 0 (delta 0)
Computing commit graph generation numbers: 100% (10591/10591), done.
[feature/myfeature ad2dc9af73] Fixed bad math operators that were causing fatal errors
 13420 files changed, 1033466 deletions(-)
 delete mode 100644 .gitattributes
 delete mode 100644 .gitignore
 delete mode 100644 .gitlab-ci.yml
[etc...]
```
