### ISSUE TITLE
PHPCS is outputing always json mode

### ISSUE THREAD

**Issue by akas84bg** [phpro/grumphp#702]
| Q               | A
| --------------- | ---
| Version         | GrumPHP version 0.9.6
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | not sure

The problem seems to be related with this: https://github.com/phpro/grumphp/blob/master/src/Task/Phpcs.php#L86

**My configuration**
```yaml
# grumphp.yml
# Please add a copy of your grumphp.yml file.
parameters:
    git_dir: .
    bin_dir: bin
    tasks: 
        phpcs:
            standard: PSR2
            show_warnings: true
            tab_width: ~
            ignore_patterns: 
                - /^vendor\/(.*)/
                - /^resources\/(.*)/
                - /^storage\/(.*)/
                - /tests\/spec\/(.*)\/
                - /database\/migrations\/(.*)
            encoding: ~
            ignore_patterns: []
            sniffs: []
            triggered_by: [php]
        phpunit:
            config_file: phpunit.xml

```

**Steps to reproduce:**
```sh
#generate some files with phpcs problems


# Your actions
# Please add the steps on how to reproduce the issue here.

# Run GrumpHP:
git add -A && git commit -m"Test"
# or
./vendor/bin/grumphp run
```

**Result:**
```
# Please add the result of the run or git commit actions here.
{"totals":{"errors":1,"warnings":2,"fixable":1},"files":{"file.php":{"errors":1,"warnings":0,"messages":[{"message":"Function closing brace must go on the next line following the body; found 1 blank lines before brace","source":"PSR2.Methods.FunctionClosingBrace.SpacingBeforeClose","severity":5,"fixable":true,"type":"ERROR","line":93,"column":5}]},"file2.php":{"errors":0,"warnings":0,"messages":[]},"file3.php":{"errors":0,"warnings":0,"messages":[]},"file4.php":{"errors":0,"warnings":0,"messages":[]},"file5.php":{"errors":0,"warnings":0,"messages":[]},"file6.php":{"errors":0,"warnings":0,"messages":[]},"file7.php":{"errors":0,"warnings":0,"messages":[]},"file8.php":{"errors":0,"warnings":1,"messages":[{"message":"Line exceeds 120 characters; contains 126 characters","source":"Generic.Files.LineLength.TooLong","severity":5,"fixable":false,"type":"WARNING","line":54,"column":126}]},"file9.php":{"errors":0,"warnings":0,"messages":[]},"file10.php":{"errors":0,"warnings":0,"messages":[]},"file11.php":{"errors":0,"warnings":0,"messages":[]},"file12.php":{"errors":0,"warnings":0,"messages":[]},"file13.php":{"errors":0,"warnings":0,"messages":[]},"file14.php":{"errors":0,"warnings":0,"messages":[]},"file15.php":{"errors":0,"warnings":0,"messages":[]},"file16.php":{"errors":0,"warnings":1,"messages":[{"message":"Line exceeds 120 characters; contains 123 characters","source":"Generic.Files.LineLength.TooLong","severity":5,"fixable":false,"type":"WARNING","line":93,"column":123}]},"file17.php":{"errors":0,"warnings":0,"messages":[]}}}

```
