### ISSUE TITLE
False positive on Psalm task

### ISSUE THREAD

**Issue by pyrsmk** [phpro/grumphp#713]
| Q               | A
| --------------- | ---
| Version         | 0.17.1
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

- when run by hand, Psalm fails on my source files, which is the expected behavior
- when Grumphp is run by a git hook, Psalm fails as expected
- but when we call `grumphp run`, the Psalm task is marked as successful

edit: I just saw that the same can happen to phpcsfixer2; I don't know it it's an expected behavior, or if I missed something in the docs

**My configuration**
```yaml
# grumphp.yml
parameters:
    stop_on_failure: true
    ignore_unstaged_changes: true
    tasks:
        composer:
            strict: true
        composer_script:
            script: spec
        git_branch_name:
            whitelist:
                - "/(feature|fix|hotfix)\\/[a-z0-9-]+/"
            blacklist:
                - master
                - develop
        jsonlint:
            detect_key_conflicts: true
        phpcpd:
            directory:
                - src
        phpcsfixer2:
            config: .php_cs.dist
        phpmnd:
            exclude:
                - RoboFile.php
                - spec
        psalm:
            threads: 2
        securitychecker: null
        yamllint: null

```

**Steps to reproduce:**
```sh
./vendor/bin/grumphp run
```
