### ISSUE TITLE
PHPCS issues are not reported during pre-commit

### ISSUE THREAD

**Issue by hussainweb** [phpro/grumphp#715]
| Q               | A
| --------------- | ---
| Version         | `0.16.2`
| Bug?            | yes (missing functionality for phpcs)
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

This issue relates to Drupal's module system but could happen to several other tools. Essentially, phpcs is reported as successful whereas it should have failed. This happens because Drupal uses a different extension for some of its files. In my case, I was writing a module file which is PHP but has an extension `.module`. The configuration allows it to get triggered correctly, but phpcs does not report any violations for Drupal coding standard.

This is the command that gets run for phpcs:
```
/vendor/bin/phpcs '--standard=Drupal,DrupalPractice' '--report=full' '--ignore=.github,.gitlab,bower_components,node_modules,vendor' '--report-json' 'web/modules/custom/axl_ks_mail/axl_ks_mail.module'
```

Even though the file is explicitly mentioned, phpcs doesn't process it because it doesn't know what's a module file. We should explicitly ask it to process it as PHP using the `--extensions` argument. Sure enough, if I run this command directly, it doesn't report violations, but this works as expected:

```
/vendor/bin/phpcs '--standard=Drupal,DrupalPractice' '--report=full' '--ignore=.github,.gitlab,bower_components,node_modules,vendor' '--report-json' 'web/modules/custom/axl_ks_mail/axl_ks_mail.module' --extensions=module
```

Now, my expectation was that it should pick the `triggered_by` list as extensions, but it doesn't. Or, there should be another configuration to specify the extensions. I think the former behaviour is sufficient. If a file is to trigger a phpcs check, that should be a valid extension.

**My configuration**
```yaml
# grumphp.yml
parameters:
  ascii:
    failed: vendor/axelerant/drupal-quality-checker/resources/grumpy.txt
    succeeded: vendor/axelerant/drupal-quality-checker/resources/happy.txt
  git_dir: .
  bin_dir: vendor/bin
  tasks:
    phplint: ~
    yamllint: ~
    composer: ~
    jsonlint: ~
    phpcpd:
      directory: './web/modules/custom'
    phpcs:
      standard:
        - Drupal
        - DrupalPractice
      ignore_patterns:
        - .github
        - .gitlab
        - bower_components
        - node_modules
        - vendor
      triggered_by:
        - php
        - module
        - inc
        - install
        - test
        - profile
        - theme
        - css
        - info
        - txt
        - md
    phpmd:
      whitelist_patterns:
        - /^web\/modules\/custom\/(.*)/
      ruleset: ['phpmd.xml']
      triggered_by: ['php']
```

**Steps to reproduce:**
```sh
# Generate empty folder
mkdir tmp
cd tmp
git init
echo "vendor" > .gitignore
pbpaste > grumphp.yml
composer require --dev phpro/grumphp

# Your actions
# Create a file with .module extension (or any other extension not typical of PHP) with coding violations.

# Run GrumpHP:
git add -A && git commit -m"Test"
# or
./vendor/bin/grumphp run
```

**Result:**
```
phpcs reports that everything is fine.
```
