### ISSUE TITLE
ECS task not working

### ISSUE THREAD

**Issue by fernandofdzcode** [phpro/grumphp#726]
| Q               | A
| --------------- | ---
| Version         | 0.17.2
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | none

Im using grumpPHP on a 4.4 symfony project. When using the ECS task with a very simple config file, it doesn't trowh any error although there are plenty.
Running ECS raw in command line works and prompts all errors.
Also, not specifying any file in the grumPHP file doesn't work either.

Im using the default config for ECS only specifiying my config file:

**My configuration**
```yaml
# grumphp.yml
    tasks:
      ecs:
        config: ./ecs.yml
# ecs.yml
services:
  PhpCsFixer\Fixer\ArrayNotation\ArraySyntaxFixer:
    syntax: short
```

**Result:**
```
# grumPHP output:
GrumPHP is sniffing your code!
Running task 1/1: Ecs... ✔

# raw ECS output:
1) src/Controller/sampleController.php

    ---------- begin diff ----------
--- Original
+++ New
@@ -12,7 +12,7 @@
      */
     public function index()
     {
-        $sample = array();
+        $sample = [];
```
