### ISSUE TITLE
Use Symfony CLI with specified .php-version 

### ISSUE THREAD

**Issue by CharlyPoppins** [phpro/grumphp#742]
| Q               | A
| --------------- | ---
| Version         | 0.17.2
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | no
| Related tickets | 

Hello,

I've multiple php versions on my local environnement
```
php -v : 7.2.27
symfony php -v : 7.4.2 (defined in file .php-version)
```

I'm trying to confiture GrumPHP  so it will use Symfony CLI with the version 7.4.2 define in file .php-version.

If this can't work, how can I specify the php path to use ? In my case `/usr/local/opt/php`

**My configuration**
```yaml
# grumphp.yml
parameters:
  git_hook_variables:
    EXEC_GRUMPHP_COMMAND: 'symfony php'
  git_dir: .
  bin_dir: bin
  tasks:
    phpstan:
      ignore_patterns: [src/Migrations]
      memory_limit: "-1"
```

**Steps to reproduce:**
```sh
# Run GrumPHP with default local PHP version
php ./vendor/bin/grumphp run
Fatal Error: composer.lock was created for PHP version 7.4 or higher but the current PHP version is 7.2.27.

# Run GrumPHP with Symfony CLI
symfony php ./vendor/bin/grumphp run
All good!
```
