### ISSUE TITLE
The executable for "phpunit" could not be found

### ISSUE THREAD

**Issue by rand0mdev** [phpro/grumphp#750]
| Q               | A
| --------------- | ---
| Version         | 0.18.0
| Bug?            | yes
| New feature?    | no
| Question?       | yes
| Documentation?  | yes
| Related tickets | 

<img width="1077" alt="Screen Shot 2020-03-27 at 5 26 39 PM" src="https://user-images.githubusercontent.com/13308700/77783141-4543fe80-7050-11ea-8858-4da1f984db83.png">

**My configuration**
```yaml
# grumphp.yml
parameters:
  git_dir: "."
  bin_dir: "./vendor/bin"
  tasks:
    phpcsfixer2:
      config: './.php_cs.dist'
    phpunit: ~
```

**Steps to reproduce:**
```sh
$ git clone https://github.com/rand0mdev/rim-edu.git
$ cd rim-edu/ && composer install
$ ./vendor/bin/grumphp run
```

**Result:**
```
The executable for "phpunit" could not be found.
To skip commit checks, add -n or --no-verify flag to commit command
```
