### ISSUE TITLE
Convention variables validation bug

### ISSUE THREAD

**Issue by janvernieuwe** [phpro/grumphp#755]
| Q               | A
| --------------- | ---
| Version         | 0.18.x
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

**My configuration**
```yaml
# grumphp.yml
parameters:
        phpparser:
            ignore_patterns: "%phpparser.ignore%"
```

# Your actions
Value is overridden with an array, the config is from a convention

# Run GrumPHP:
vendor/bin/grumphp/run
```

**Result:**
```
The option "ignore_patterns" with value "%phpparser.ignore%" is expected to be of type "array", but is of type "string".
```
