### ISSUE TITLE
Getting 'git' is not recognized as an internal or external command Even git is installed correctly

### ISSUE THREAD

**Issue by doroness** [phpro/grumphp#759]
Trying to run grumphp. Git is installed and set correctly on PATH. (I can even run git on vendor/bin)
But I keep getting this error 

> In Repository.php line 558:
>                                                                         
>   Error while running git command:                                      
>   git --git-dir "D:\local sites\ground-zero\app\public\wp-content\plu   
>   gins\WordPress-Widget-Boilerplate\.git" --work-tree "D:/local sites   
>   /ground-zero/app/public/wp-content/plugins/WordPress-Widget-Boilerp   
>   late" ls-files "D:\local sites\ground-zero\app\public\wp-content\pl   
>   ugins\WordPress-Widget-Boilerplate\vendor\bin"                        
>                                                                         
>   'git' is not recognized as an internal or external command,           
>   operable program or batch file.

grumphp.yml is on project root folder (...\app\public\wp-content\plugins\WordPress-Widget-Boilerplate\grumphp.yml)

| Q               | A
| --------------- | ---
| Version         | `^0.16.2'
| Bug?            | yes
| New feature?    | no
| Question?       | yes
| Related tickets | git

**My configuration**
```yaml
# grumphp.yml
parameters:
    git_dir: .git
    bin_dir: vendor/bin
    process_timeout: 120
    tasks:
      securitychecker:
      composer:
      jsonlint:
      xmllint:
      yamllint:
      phplint:
        exclude:
          - vendor/
      phpcs:
        metadata:
          priority: 200
      phpcsfixer2:
        allow_risky: true
        config: '.php_cs.dist'
        metadata:
          priority: 300
      phpparser:
        visitors:
          forbidden_function_calls:
            blacklist:
              - "exit"
              - "var_dump"
      phpversion:
        project: '7.1'
      phpmd:
        exclude: ['vendor']
        ruleset: ['phpmd.xml']

**Steps to reproduce:**
Get composer file from here
Add to project root directory
run composer install

# Your actions
# Please add the steps on how to reproduce the issue here.

# Run GrumPHP:

./vendor/bin/grumphp run
```

**Result:**
```
# Please add the result of the run or git commit actions here.
```

In Repository.php line 558:
                                                                        
  Error while running git command:                                      
  git --git-dir "D:\local sites\ground-zero\app\public\wp-content\plu   
  gins\WordPress-Widget-Boilerplate\.git" --work-tree "D:/local sites   
  /ground-zero/app/public/wp-content/plugins/WordPress-Widget-Boilerp   
  late" ls-files "D:\local sites\ground-zero\app\public\wp-content\pl   
  ugins\WordPress-Widget-Boilerplate\vendor\bin"                        
                                                                        
  'git' is not recognized as an internal or external command,           
  operable program or batch file.
