### ISSUE TITLE
Unable to inject own Symfony service into grumphp custom task

### ISSUE THREAD

**Issue by patpilus** [phpro/grumphp#764]
| Q               | A
| --------------- | ---
| Version         | `0.18.0` as well as `dev-master`
| Bug?            | yes
| New feature?    | no
| Question?       | yes
| Documentation?  | no
| Related tickets | -

I'm trying to extend CloverCoverage task to allow combining several coverage reports (let's call it `my_perfect_project.coverage_collector`) into one and check for the appropriate coverage level. I planned to write custom service that can handle  most of the job and inject it into the task.

The issue I'm facing is that it's unable to inject my own service because it's not available in the container built by `/app/vendor/phpro/grumphp/src/Configuration/ContainerFactory.php`.

I'm getting such error message
```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "task_runner" has a dependency on a non-existent service "my_perfect_project.coverage_collector"
```

The service is correctly defined what can be proven by executing `bin/console debug:container my_perfect_project.coverage_collector`. Here's the output:
```
root@ce1d13263e5b:/app# bin/console debug:container my_perfect_project.coverage_collector

Information for Service "my_perfect_project.coverage_collector"
===============================================================

 ---------------- ------------------------------------------------------------ 
  Option           Value                                                       
 ---------------- ------------------------------------------------------------ 
  Service ID       my_perfect_project.coverage_collector                       
  Class            MyPerfectProject\Service\CodeCoverage\CoverageCollector  
  Tags             -                                                           
  Public           yes                                                         
  Synthetic        no                                                          
  Lazy             no                                                          
  Shared           yes                                                         
  Abstract         no                                                          
  Autowired        no                                                          
  Autoconfigured   no                                                          
 ---------------- ------------------------------------------------------------ 

```

Please advice how to inject custom Symfony service into custom grumphp task. 

Thanks!

**My configuration**
```yaml
parameters:
    process_timeout: 500
    git_dir: .
    bin_dir: vendor/bin
    ascii:
        succeeded:
            - './bin/resources/grumphp/successful_ascii.txt'
            - './bin/resources/grumphp/successful_ascii2.txt'
        failed:
            - './bin/resources/grumphp/failed_ascii.txt'
            - './bin/resources/grumphp/failed_ascii2.txt'
    tasks:
        clover_coverage_combined:
            input_coverages_extension: cov
            clover_file: coverage.xml
            level: 90

services:
    task.combinedclovercoverage:
        class: MyPerfectProject\Tests\GrumPhpTasks\CombinedCloverCoverage
        arguments:
            - '@my_perfect_project.coverage_collector'
            - '@filesystem'
        tags:
            - {name: grumphp.task, task: clover_coverage_combined}
```

**Steps to reproduce:**
- write custom service
- write custom grumphp task
- inject the service into the custom task
- execute the task

# Run GrumPHP:
`./vendor/bin/grumphp --tasks=clover_coverage_combined -vvv`

**Result:**
```
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "task_runner" has a dependency on a non-existent service "my_perfect_project.coverage_collector". in /app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on line 86

Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "task_runner" has a dependency on a non-existent service "my_perfect_project.coverage_collector". in /app/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on line 86

Call Stack:
    0.0004     401808   1. {main}() /app/vendor/phpro/grumphp/bin/grumphp:0
    0.0004     402128   2. {closure:/app/vendor/phpro/grumphp/bin/grumphp:8-51}() /app/vendor/phpro/grumphp/bin/grumphp:51
    0.0330    4547352   3. GrumPHP\Configuration\ContainerFactory::build() /app/vendor/phpro/grumphp/bin/grumphp:46
    0.0683    5321088   4. GrumPHP\Configuration\ContainerBuilder::buildFromConfiguration() /app/vendor/phpro/grumphp/src/Configuration/ContainerFactory.php:24
    0.6128    7697904   5. Symfony\Component\DependencyInjection\ContainerBuilder->compile() /app/vendor/phpro/grumphp/src/Configuration/ContainerBuilder.php:54
    0.6245    7703632   6. Symfony\Component\DependencyInjection\Compiler\Compiler->compile() /app/vendor/symfony/dependency-injection/ContainerBuilder.php:762
```
