### ISSUE TITLE
SerializationException when running in parallel

### ISSUE THREAD

**Issue by R4c00n** [phpro/grumphp#771]
| Q               | A
| --------------- | ---
| Version         | `0.19.0`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | n/a

When running GrumPHP in parallel mode and without any staged files it get a `Uncaught Amp\Serialization\SerializationException` in all tasks.

As soon as I stage a file, all tasks are running successfully.

**My configuration**
```yaml
# grumphp.yml
grumphp:
    tasks:
        phplint:
            exclude:
                - vendor
            triggered_by: ['php']
        phpcs:
            standard:
                - PSR12
            whitelist_patterns:
                - src
                - test
        phpunit:
            config_file: phpunit.xml
            always_execute: true
        phpstan:
            level: 8
```

**Steps to reproduce:**
```sh
# Generate empty folder
mkdir tmp
cd tmp
git init
echo "vendor" > .gitignore
pbpaste > grumphp.yml
composer require --dev phpro/grumphp

# Make sure not to stage any files

./vendor/bin/grumphp run
```

**Result:**
```
phplint
=======

Uncaught Amp\Serialization\SerializationException in worker with message "The given data could not be serialized: Argument 1 passed to Doctrine\Common\Collections\ArrayCollection::createFrom() must be of the type array, null given, called in /Users/marcelkempf/workspace/vv-fra-heimdall/vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php on line 334" and code "0"; use Amp\Parallel\Worker\TaskFailureException::getOriginalTrace() for the stack trace in the worker

phpcs
=====

Uncaught Amp\Serialization\SerializationException in worker with message "The given data could not be serialized: Argument 1 passed to Doctrine\Common\Collections\ArrayCollection::createFrom() must be of the type array, null given, called in /Users/marcelkempf/workspace/vv-fra-heimdall/vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php on line 334" and code "0"; use Amp\Parallel\Worker\TaskFailureException::getOriginalTrace() for the stack trace in the worker

phpunit
=======

Uncaught Amp\Serialization\SerializationException in worker with message "The given data could not be serialized: Argument 1 passed to Doctrine\Common\Collections\ArrayCollection::createFrom() must be of the type array, null given, called in /Users/marcelkempf/workspace/vv-fra-heimdall/vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php on line 334" and code "0"; use Amp\Parallel\Worker\TaskFailureException::getOriginalTrace() for the stack trace in the worker

phpstan
=======

Uncaught Amp\Serialization\SerializationException in worker with message "The given data could not be serialized: Argument 1 passed to Doctrine\Common\Collections\ArrayCollection::createFrom() must be of the type array, null given, called in /Users/marcelkempf/workspace/vv-fra-heimdall/vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php on line 334" and code "0"; use Amp\Parallel\Worker\TaskFailureException::getOriginalTrace() for the stack trace in the worker
To skip commit checks, add -n or --no-verify flag to commit command
```
