### ISSUE TITLE
Issues with "type_scope_conventions"

### ISSUE THREAD

**Issue by adaniloff** [phpro/grumphp#778]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 0.15.2
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | yes

Hi there, 2 issues:
1. Documentation issues about `type_scope_conventions`

```yaml
type_scope_conventions:
  - types:
    - build
    - ci
    - chore
    - docs
    - feat
    - fix
    - perf
    - refactor
    - revert
    - style
    - test
  - scopes: []
```
should be (both for `type` and `scope` i doc btw): 

```yaml
type_scope_conventions:
  types:
    - build
    - ci
    - chore
    - docs
    - feat
    - fix
    - perf
    - refactor
    - revert
    - style
    - test
  scopes: []
```

Otherwise the conf is not loaded.

2. `enforce_capitalized_subject` does not work well with `type_scope_conventions` defined:
- "fix: Some capitalized subject" ----------> fails (but should not)
- "Fix: some uncapitalized subject" ------>  succeed (but should fail)
