### ISSUE TITLE
GrumPHP not executed with the right version of PHP

### ISSUE THREAD

**Issue by benjamintoussaint** [phpro/grumphp#805]
| Q               | A
| --------------- | ---
| Version         | 0.18.1
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | n/a

Even after having configured the "exec" path for PHP, I've got this error:

```
Fatal Error: composer.lock was created for PHP version 7.4 or higher but the current PHP version is 7.3.11.
```

**My configuration**
```yaml
parameters:
    git_dir: .
    bin_dir: vendor/bin
    git_hook_variables:
        EXEC_GRUMPHP_COMMAND: /usr/local/bin/php
    tasks:
        phpstan:
            configuration: phpstan.neon
            level: 8
            triggered_by: ['php']
        phpcsfixer2:
            allow_risky: false
            cache_file: ~
            config: .php_cs.dist
            using_cache: true
            config_contains_finder: true
            verbose: false
            diff: false
            triggered_by: ['php']
        yamllint:
            parse_custom_tags: true
```

**Here's the content of my `.git/hooks/pre-commit` file:**

```bash
#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

# Fetch the GIT diff and format it as command input:
DIFF=$(git -c diff.mnemonicprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged | cat)

# Grumphp env vars
export GRUMPHP_GIT_WORKING_DIR=$(git rev-parse --show-toplevel)

# Run GrumPHP
(cd "./" && printf "%s\n" "${DIFF}" | '/usr/local/bin/php' 'vendor/phpro/grumphp/bin/grumphp' 'git:pre-commit' '--skip-success-output')
```

**How do I currently fix it:**

I need to manually add this line prior to running GrumPHP to make it work:

```bash
PATH=/usr/local/bin:$PATH
```

Do you have any idea of how I could make it work only with the `EXEC_GRUMPHP_COMMAND` option?

**Comment by veewee** [comment]
Hello @benjamintoussaint 

Since [https://github.com/phpro/grumphp/releases/tag/v0.20.0](v0.20.0), you can add mulitple ENV vars directly to the git hook:

```yaml
grumphp:
  git_hook_variables:
    ENV:
      PATH: '/usr/local/bin:$PATH'
```

(Don't forget to run `grumphp git:init` after changing these params)
