### ISSUE TITLE
git_commit_message does not work on newer version

### ISSUE THREAD

**Issue by GlennM** [phpro/grumphp#813]
| Q               | A
| --------------- | ---
| Version         | `0.21.0`
| Bug?            | yes
| New feature?    | no
| Question?       | yes
| Documentation?  |no
| Related tickets | 

Upgraded from `"phpro/grumphp": "^0.17.0"` to latest version.
Changed config from "parameters" to "grumphp": in my `grumphp.yml` file

Had no issues with the config on version `0.17.2`.

**My configuration**
```yaml
# grumphp.yml
grumphp:
    tasks:
      phpcs: null
      yamllint: null
      git_branch_name:
        whitelist:
            - "/(release|feature|hotfix|fix|chore)\\/([a-z0-9-.]+)/"
        blacklist:
            - "develop"
            - "master"
      git_commit_message:
          allow_empty_message: false
          enforce_capitalized_subject: false
          enforce_no_subject_trailing_period: true
          enforce_single_lined_subject: true
          max_body_width: 72
          max_subject_width: 72
          type_scope_conventions:
            - types:
              - build
              - ci
              - chore
              - docs
              - feat
              - fix
              - perf
              - refactor
              - revert
              - style
              - test
              - WIP
              - test
```

**Steps to reproduce:**

# Your actions
- Trying to commit with message
`build: Update GrumPHP config`

**Result:**
```
GrumPHP detected a pre-commit command.
GrumPHP is sniffing your code!

Running tasks with priority 0!
==============================

Running task 1/3: phpcs... 
Running task 2/3: yamllint... 
Running task 3/3: git_branch_name... ✔
GrumPHP detected a commit-msg command.
GrumPHP is sniffing your code!

Running tasks with priority 0!
==============================

Running task 1/1: git_commit_message... ✘

NOPE

git_commit_message
==================

Error while running git command:
'git' '--git-dir' '<project-dir>/.git' '--work-tree' '<project-dir>/vb' 'config' '--get' 'core.commentChar'
```
