### ISSUE TITLE
grumphp is really verbose in a CI

### ISSUE THREAD

**Issue by prudloff-insite** [phpro/grumphp#817]
| Q               | A
| --------------- | ---
| Version         | 0.22.0
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

When running in a CI, grumphp is really verbose because the `overwrite()` method of `ConsoleSectionOutput` is not able to replace the text.

It would be nice to have an option to disable this behaviour and simply display the result at the end.

**My configuration**
```yaml
---
grumphp:
  ascii:
    failed: ~
    succeeded: ~
  tasks:
    composer: ~
    jsonlint: ~
    yamllint: ~
    xmllint: ~
    phpcs:
      standard: tests/phpcs.xml
      triggered_by:
        - php
        - module
        - inc
        - install
        - test
        - profile
        - theme
        - info
        - txt
        - md
    phpmd:
      ruleset:
        - tests/phpmd.xml
    git_blacklist:
      keywords:
        - "kint("
        - "|raw"
        - "autoescape"
      triggered_by:
        - twig
```

**Steps to reproduce:**
You can simulate this behaviour like this:
```sh
./vendor/bin/grumphp run | cat
```

**Result:**
```
GrumPHP is sniffing your code!

Running tasks with priority 0!
==============================

Running task 1/6: composer... 
Running task 2/6: jsonlint... 
Running task 3/6: yamllint... 
Running task 4/6: xmllint... 
Running task 5/6: phpcs... 
Running task 6/6: phpmd... 
Running task 1/6: composer... 
Running task 2/6: jsonlint... 
Running task 3/6: yamllint... 
Running task 4/6: xmllint... ✔
Running task 5/6: phpcs... 
Running task 6/6: phpmd... 
Running task 1/6: composer... 
Running task 2/6: jsonlint... ✔
Running task 3/6: yamllint... 
Running task 4/6: xmllint... ✔
Running task 5/6: phpcs... 
Running task 6/6: phpmd... 
Running task 1/6: composer... 
Running task 2/6: jsonlint... ✔
Running task 3/6: yamllint... ✔
Running task 4/6: xmllint... ✔
Running task 5/6: phpcs... 
Running task 6/6: phpmd... 
Running task 1/6: composer... ✔
Running task 2/6: jsonlint... ✔
Running task 3/6: yamllint... ✔
Running task 4/6: xmllint... ✔
Running task 5/6: phpcs... 
Running task 6/6: phpmd... 
Running task 1/6: composer... ✔
Running task 2/6: jsonlint... ✔
Running task 3/6: yamllint... ✔
Running task 4/6: xmllint... ✔
Running task 5/6: phpcs... ✔
Running task 6/6: phpmd... 
Running task 1/6: composer... ✔
Running task 2/6: jsonlint... ✔
Running task 3/6: yamllint... ✔
Running task 4/6: xmllint... ✔
Running task 5/6: phpcs... ✔
Running task 6/6: phpmd... ✔
```
