### ISSUE TITLE
Call to undefined function get_debug_type()

### ISSUE THREAD

**Issue by prudloff-insite** [phpro/grumphp#832]
| Q               | A
| --------------- | ---
| Version         | 1.1.0
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets |

The 1.1.0 PHAR crashes when calling `run`.
I don't have this issue with the 1.0.0 PHAR or with 1.1.0 installed locally by Composer.

**My configuration**
```yaml
---
grumphp:
  ascii:
    failed: ~
    succeeded: ~
  tasks:
    composer: ~
    jsonlint: ~
    yamllint: ~
    composer_normalize:
      use_standalone: true
    xmllint:
      ignore_patterns:
        - .docksal/etc/solr/
    phpcs:
      standard: tests/phpcs.xml
      triggered_by:
        - php
        - module
        - inc
        - install
        - test
        - profile
        - theme
        - info
        - txt
        - md
    phpmd:
      ruleset:
        - tests/phpmd.xml
```

Note that I don't have the issue if I only keep this part of the config file:
```yaml
---
grumphp:
  ascii:
    failed: ~
    succeeded: ~
  tasks:
    composer: ~
    jsonlint: ~
    yamllint: ~
```

**Steps to reproduce:**
```sh
phive install grumphp
grumphp run
```

**Result:**
```
PHP Fatal error:  Uncaught Error: Call to undefined function get_debug_type() in phar:///home/pierre/.phive/phars/grumphp-1.1.0.phar/vendor/symfony/options-resolver/OptionsResolver.php:975
Stack trace:
#0 phar:///home/pierre/.phive/phars/grumphp-1.1.0.phar/vendor/symfony/options-resolver/OptionsResolver.php(864): _HumbugBox7411c7c548dd\Symfony\Component\OptionsResolver\OptionsResolver->verifyTypes()
#1 phar:///home/pierre/.phive/phars/grumphp-1.1.0.phar/vendor/symfony/options-resolver/OptionsResolver.php(774): _HumbugBox7411c7c548dd\Symfony\Component\OptionsResolver\OptionsResolver->offsetGet()
#2 phar:///home/pierre/.phive/phars/grumphp-1.1.0.phar/src/Configuration/Resolver/TaskConfigResolver.php(35): _HumbugBox7411c7c548dd\Symfony\Component\OptionsResolver\OptionsResolver->resolve()
#3 phar:///home/pierre/.phive/phars/grumphp-1.1.0.phar/src/Configuration/Compiler/TaskCompilerPass.php(48): GrumPHP\Configuration\Resolver\TaskConfigResolver->resolve()
#4 phar:///home/pierre/.phive/phars/grumphp-1.1.0.phar/src/Task/Config/LazyTa in phar:///home/pierre/.phive/phars/grumphp-1.1.0.phar/vendor/symfony/options-resolver/OptionsResolver.php on line 975
```
