### ISSUE TITLE
grumphp deletes entire repo contents with ignore_unstaged_changes: true

### ISSUE THREAD

**Issue by dshafik** [phpro/grumphp#859]
| Q               | A
| --------------- | ---
| Version         | GrumPHP 1.3.0
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | 

**My configuration**
```yaml
grumphp:
    ignore_unstaged_changes: true
    ascii:
        succeeded: ~
        failed: ~
    fixer:
        enabled: true
        fix_by_default: true
    parallel:
        enabled: true
        max_workers: 8
    hide_circumvention_tip: false
    tasks:
        phpversion:
            project: '7.3'
        phpstan:
            metadata:
                blocking: false
            use_grumphp_paths: false
            configuration: phpstan.neon.dist
        psalm:
            config: psalm.xml
            no_cache: true
            threads: 8
        phpcsfixer2:
            using_cache: true
            config: .php_cs.dist
            verbose: true
```

**Steps to reproduce:**

1. Add `ignore_unstaged_changes: true` to your grumphp.yaml
2. Edit two files
3. Stage one file
4. Commit

**Result:**

grumphp shows a notice that it is stashing changes, run the tasks successfully, and gives the notice it's restoring the stash. **The commit succeeds**.

# **All** files in the repo are `git rm`'ed, `git ls-files` returns nothing.

You can see this in action up till the point grumphp outputs task output (sensitive). As soon as the tasks are finished it does the standard grumphp commit & unstash, and everything is deleted:

https://user-images.githubusercontent.com/58074/104081078-3e523b00-51e1-11eb-9efa-54be313b598e.mov
