### ISSUE TITLE
`stop_on_failure: true` and `blocking: false` don't work as expected

### ISSUE THREAD

**Issue by dshafik** [phpro/grumphp#860]
| Q               | A
| --------------- | ---
| Version         |  1.3.0
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no?
| Related tickets | 

If `stop_on_failure` is set to `true`, and a task has `blocking` set to `false`, GrumPHP will still stop execution rather than ignoring the failure as is done when `stop_one_failure: false`.

**My configuration**
```yaml
grumphp:
    stop_on_failure: true
    tasks:
        phpstan:
            metadata:
                blocking: false
            use_grumphp_paths: false
            configuration: phpstan.neon.dist
```

**Steps to reproduce:**

Call `./vendor/bin/grumphp run` with one task that will fail set to `blocking: false` (e.g. set `process_timeout: 1` and put a `sleep(2)` in a phpunit test.

**Result:**

<img width="460" alt="image" src="https://user-images.githubusercontent.com/58074/104285341-58ea1580-5468-11eb-862f-b8e9de548a88.png">

As you can see, `phpstan` has an orange `x` indicating it failed but should be ignored, and then GrumPHP `Aborted…`
