### ISSUE TITLE
Pass CLI args/options directly into grumphp

### ISSUE THREAD

**Issue by cnizzardini** [phpro/grumphp#874]
| Q               | A
| --------------- | ---
| Version         | `1.3`
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no

It would be nice if we could pass CLI switch and arguments directly into grumphp setup. It would make it easy for new users to migrate setups like this to grumphp instead of having to learn the YAML config:

```json
    "scripts": {
        "test": "phpunit --colors=always",
        "phpcs":  "phpcs --colors -p --standard=vendor/cakephp/cakephp-codesniffer/CakePHP plugins/*/src",
        "phpcbf": "phpcbf --colors -p --standard=vendor/cakephp/cakephp-codesniffer/CakePHP plugins/*/src",
        "phpstan": "phpstan analyse plugins/*/src",
        "phpmd": "phpmd plugins --exclude tests,assets,config ansi phpmd.xml",
```

Example:

```yaml
grumphp:
    tasks:
      phpcs:
          arg: "--colors -p --standard=vendor/cakephp/cakephp-codesniffer/CakePHP plugins/*/src"
```
