### ISSUE TITLE
Twigcs fails if the given path doesn't exist

### ISSUE THREAD

**Issue by MPParsley** [phpro/grumphp#876]
| Q               | A
| --------------- | ---
| Version         | `1.3.1`
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | yes
| Related tickets | -

**My configuration**
```yaml
# grumphp.yml
grumphp:
    tasks:
        twigcs:
            path: 'templates'
            severity: 'warning'
            ruleset: 'FriendsOfTwig\Twigcs\Ruleset\Official'
            triggered_by: ['twig']
            exclude: []
```

**Steps to reproduce:**
```sh
$ vendor/bin/grumphp run --tasks twigcs
```

**Result:**
```
GrumPHP is sniffing your code!
Running tasks with priority 0!
==============================

Running task 1/1: twigcs... ✘

twigcs
======

In ConfigResolver.php line 239:
                                         
  The path "templates" is not readable.  
```
