### ISSUE TITLE
Paratest "parallel" argument passed through incorrectly

### ISSUE THREAD

**Issue by dshafik** [phpro/grumphp#887]
| Q               | A
| --------------- | ---
| Version         | 1.3.1
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets | n/a

**My configuration**
```yaml
grumphp:
    tasks:
        paratest:
            always_execute: false
            processes: half
```

**Steps to reproduce:**
```sh
./vendor/bin/grumphp run -vvv | grep paratest
```

**Result:**

This will result in the following output (you can Ctrl+C once you see it):

```
Command: '$PWD/vendor/bin/paratest' '-p=half'
```

Showing that it passed in `-p=half` to `paratest`, however the correct format is `-p half` (short flag, with the space) **or** `--processes=half` (full name with the `=`) — this results in the argument being ignored and it always uses the default of `auto` which means that it uses all available cores.
