### ISSUE TITLE
File check always fail after a file is deleted from the repository

### ISSUE THREAD

**Issue by lcdss** [phpro/grumphp#912]
| Q               | A
| --------------- | ---
| Version         | 1.3.2
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets |

```
file_size
=========

Large files detected:
- Controller.php exceeded the maximum size of 100M.
- BroadcastServiceProvider.php exceeded the maximum size of 100M.
- welcome.blade.php exceeded the maximum size of 100M.
- channels.php exceeded the maximum size of 100M.
- web.php exceeded the maximum size of 100M.
```
```
grumphp:
  hooks_dir: ..
  tasks:
    file_size:
      max_size: 100M
      ignore_patterns:
        - composer.lock
```

This happens only with deleted files. If I discard the deletion of one of these files, it will not be detected as a infraction by the file_size task.
