### ISSUE TITLE
PHPLint task Exclude not excluding vendor

### ISSUE THREAD

**Issue by steveclifton** [phpro/grumphp#922]
| Q               | A
| --------------- | ---
| Version         | 1.4.0
| Bug?            | yes
| New feature?    | no
| Question?       | maybe
| Documentation?  | no
| Related tickets | 

We recently updated from v0.18 to 1.4.0 and are experiencing an issue that PHPLint is not excluding the `vendor` directory.. it appears to me that everything is correct with my config?

**My configuration**
```
grumphp:
    tasks:
        composer:
        composer_normalize:
        phplint:
            exclude:
                - 'vendor'
            triggered_by: ['php']
```

**Steps to reproduce:**
```
git commit -m "Test Message"
```

**Result:**
```
phplint
=======

Fatal error: Array and string offset access syntax with curly braces is no longer supported in /path/vendor/jakub-onderka/php-parallel-lint/src/Settings.php on line 145

PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /path/vendor/jakub-onderka/php-parallel-lint/src/Settings.php on line 145
To skip commit checks, add -n or --no-verify flag to commit command

```
