### ISSUE TITLE
vscode shows alert on phpcsfixer

### ISSUE THREAD

**Issue by crissi** [phpro/grumphp#975]
| Q               | A
| --------------- | ---
| Version         | `vendor/bin/grumphp -V`
| Question?       | yes

I want phpcsfixer to fix my files and commit them. 

But right now it fixes the files, but **do not** commit them and this alert shows.

**My configuration**
```yaml

grumphp:
    fixer:
        enabled: true
        fix_by_default: true
    tasks:
        phpcsfixer:
            config: .php-cs-fixer.dist.php
    git_hook_variables:
        EXEC_GRUMPHP_COMMAND: 'docker-compose exec -T php'
```
**Steps to reproduce:**

git add -A && git commit -m"Test"

**Result:**
![image](https://user-images.githubusercontent.com/3076578/149737015-162d5219-b150-487d-802f-fdbf87b320da.png)

![image](https://user-images.githubusercontent.com/3076578/149737589-f752bb0a-6308-408d-8b51-31923317dc43.png)
