### ISSUE TITLE
phpcs --file-list parameter causes incorrect results

### ISSUE THREAD

**Issue by MelchiorKokernoot** [phpro/grumphp#987]
| Q               | A
| --------------- | ---
| Version         | `1.8`
| Bug?            | no
| New feature?    | no
| Question?       | yes
| Documentation?  | no

When running the Phpcs task with the --file-list parameter GrumPHP finds no errors,
when commenting this line at:

`phpro/grumphp/src/Task/Phpcs.php:87`
```php
$arguments->add('--file-list='.$tmpFile);
```

The output shows the expected errors:

**My configuration**
```yaml
grumphp:
  parallel:
    enabled: true
    max_workers: 32
  stop_on_failure: true
  hide_circumvention_tip: true
  process_timeout: 240
  tasks:
    phpcs:
      standard: "phpcs.xml"
      triggered_by: [ "php"]

```

**Steps to reproduce:**
`vendor\bin\grumphp.bat run` -> 
![image](https://user-images.githubusercontent.com/23347384/154034170-f0cea272-a368-4dbe-a732-7ea5a3fea050.png)

comment:

`phpro/grumphp/src/Task/Phpcs.php:87`
```php
$arguments->add('--file-list='.$tmpFile);
```
`vendor\bin\grumphp.bat run` -> 
![image](https://user-images.githubusercontent.com/23347384/154034283-6f3df3d6-33e8-4a57-8b4e-9a940fe778cd.png)

**Result:**
```
# Please add the result of the run or git commit actions here.
```
`vendor\bin\grumphp.bat run` -> 
![image](https://user-images.githubusercontent.com/23347384/154034170-f0cea272-a368-4dbe-a732-7ea5a3fea050.png)

comment:

`phpro/grumphp/src/Task/Phpcs.php:87`
```php
$arguments->add('--file-list='.$tmpFile);
```
`vendor\bin\grumphp.bat run` -> 
![image](https://user-images.githubusercontent.com/23347384/154034283-6f3df3d6-33e8-4a57-8b4e-9a940fe778cd.png)
