### ISSUE TITLE
PhpMnd: Remove --non-zero-exit-on-violation option

### ISSUE THREAD

**Issue by kukukk** [phpro/grumphp#990]
| Q               | A
| --------------- | ---
| Version         | 1.8.1
| Bug?            | yes
| New feature?    | no
| Question?       | no
| Documentation?  | no
| Related tickets |

In the master version of PhpMnd the `--non-zero-exit-on-violation` option was removed: https://github.com/povils/phpmnd/commit/028e0e0d1e9ed73d9468b8b724453401e9a7400c

**My configuration**
```yaml
grumphp:
  tasks:
    phpmnd:
      directory: './app'
      whitelist_patterns: []
      exclude: ['Providers']
      exclude_name: []
      exclude_path: []
      extensions: []
      hint: false
      ignore_funcs: []
      ignore_numbers: []
      ignore_strings: []
      strings: false
      triggered_by: ['php']
```

**Steps to reproduce:**
```sh
./vendor/bin/grumphp run
```

**Result:**
```
phpmnd
======

phpmnd version 2.5.0 by Povilas Susinskas

  The "--non-zero-exit-on-violation" option does not exist.
```
